package compiler

import (
	"encoding/hex"
	"fmt"
	"math"
	"strconv"
	"strings"
)

func validateBunCore(core coreProgram, runtime backendRuntimeInputs) error {
	if err := validateLanguageCore(core, runtime, "Bun", func(operation runtimeOperationID) bool {
		_, ok := bunStdFunction(operation)
		return ok
	}); err != nil {
		return err
	}
	for _, function := range core.Functions {
		if function.ID != "root.main" {
			continue
		}
		// A command-line main takes the argument vector or nothing at all.
		if len(function.Parameters) > 1 ||
			(len(function.Parameters) == 1 && function.Parameters[0].Type != "string[]") {
			return bunLoweringError(function.Location, "root.main must accept no parameters or one string[] parameter")
		}
	}
	return nil
}

func bunLoweringError(location coreLocation, format string, arguments ...any) error {
	return backendLoweringError("Bun", location, format, arguments...)
}

func generateBun(core coreProgram) (string, error) {
	runtime, err := runtimeInputsForCore(core)
	if err != nil {
		return "", err
	}
	if err := validateBunCore(core, runtime); err != nil {
		return "", err
	}
	generator := newBunGenerator(core)
	generator.runtime = runtime
	return generator.generate()
}

type bunLambda struct {
	id         string
	expression coreExpression
}

type bunVariant struct {
	union string
	name  string
	tag   int
}

type bunGenerator struct {
	core         coreProgram
	functions    map[string]coreFunction
	constants    map[string]coreConstant
	variants     map[string]bunVariant
	lambdas      []bunLambda
	output       strings.Builder
	temporary    int
	scopes       int
	locals       map[string]string
	classes      map[string]coreClass
	errorClasses map[string]bool
	runtime      backendRuntimeInputs
}

func newBunGenerator(core coreProgram) *bunGenerator {
	generator := &bunGenerator{
		core:         core,
		functions:    make(map[string]coreFunction, len(core.Functions)),
		constants:    make(map[string]coreConstant, len(core.Constants)),
		variants:     make(map[string]bunVariant),
		classes:      make(map[string]coreClass, len(core.Classes)),
		errorClasses: make(map[string]bool),
	}
	for _, function := range core.Functions {
		generator.functions[function.ID] = function
	}
	for _, constant := range core.Constants {
		generator.constants[constant.ID] = constant
	}
	for _, union := range core.Unions {
		for _, variant := range union.Variants {
			name, _ := coreDeclarationName(variant.ID)
			generator.variants[variant.ID] = bunVariant{union: union.ID, name: name, tag: variant.Tag}
		}
	}
	for _, class := range core.Classes {
		generator.classes[class.ID] = class
		if class.Error {
			generator.errorClasses[class.ID] = true
		}
	}
	return generator
}

func (g *bunGenerator) generate() (string, error) {
	g.line(0, `// Generated by Slick. Compiler-owned Bun runtime ABI 1.`)
	g.line(0, `import * as slick from "@slick/runtime";`)
	g.line(0, "")
	g.emitTypeDescriptors()
	for _, constant := range g.core.Constants {
		literal, err := g.literal(constant.Value)
		if err != nil {
			return "", bunLoweringError(constant.Location, "constant %s: %v", constant.ID, err)
		}
		g.line(0, "function %s() { return %s; }", bunConstantName(constant.ID), literal)
	}
	if len(g.core.Constants) > 0 {
		g.line(0, "")
	}
	for _, function := range g.core.Functions {
		if err := g.function(function); err != nil {
			return "", err
		}
		g.line(0, "")
	}
	if err := g.emitLambdas(); err != nil {
		return "", err
	}
	g.emitDispatchTables()
	main := g.functions["root.main"]
	entry := "null"
	if len(main.Parameters) == 1 {
		entry = "\"arguments\""
	}
	g.line(0, "await slick.slickRun(import.meta.url, {")
	g.line(1, "types: SLICK_TYPES,")
	g.line(1, "functions: SLICK_FUNCTIONS,")
	g.line(1, "methods: SLICK_METHODS,")
	g.line(1, "callables: SLICK_CALLABLES,")
	g.line(1, "operations: SLICK_OPERATIONS,")
	g.line(1, "entry: %s,", entry)
	g.line(1, "status: %t,", main.Result == stdProcessStatusName)
	g.line(0, "});")
	return g.output.String(), nil
}

// emitTypeDescriptors publishes each declaration's shape, including the JSON
// name and declared type of every field, so descriptor-driven runtime behavior
// such as typed JSON never needs host reflection.
func (g *bunGenerator) emitTypeDescriptors() {
	field := func(name, jsonName, typ string) string {
		if jsonName == "" {
			jsonName = name
		}
		return fmt.Sprintf("{ name: %s, json_name: %s, typ: %s }",
			bunStringLiteral(name), bunStringLiteral(jsonName), bunStringLiteral(typ))
	}
	g.line(0, "const SLICK_TYPES = [")
	for _, class := range g.core.Classes {
		fields := make([]string, 0, len(class.Fields))
		for _, declared := range class.Fields {
			fields = append(fields, field(declared.Name, declared.JSONName, declared.Type))
		}
		methods := make([]string, 0, len(class.Methods))
		for _, method := range class.Methods {
			name, _ := coreDeclarationName(method.ID)
			methods = append(methods, bunStringLiteral(name))
		}
		interfaces := make([]string, 0, len(class.Interfaces))
		for _, iface := range class.Interfaces {
			interfaces = append(interfaces, bunStringLiteral(iface))
		}
		g.line(1, "{ name: %s, kind: \"class\", fields: [%s], methods: [%s], interfaces: [%s], variants: [] },",
			bunStringLiteral(class.ID), strings.Join(fields, ", "), strings.Join(methods, ", "), strings.Join(interfaces, ", "))
	}
	for _, iface := range g.core.Interfaces {
		methods := make([]string, 0, len(iface.Methods))
		for _, method := range iface.Methods {
			name, _ := coreDeclarationName(method.ID)
			methods = append(methods, bunStringLiteral(name))
		}
		g.line(1, "{ name: %s, kind: \"interface\", fields: [], methods: [%s], interfaces: [], variants: [] },",
			bunStringLiteral(iface.ID), strings.Join(methods, ", "))
	}
	for _, union := range g.core.Unions {
		variants := make([]string, 0, len(union.Variants))
		for _, variant := range union.Variants {
			name, _ := coreDeclarationName(variant.ID)
			fields := make([]string, 0, len(variant.Fields))
			for _, declared := range variant.Fields {
				fields = append(fields, field(declared.Name, declared.JSONName, declared.Type))
			}
			variants = append(variants, fmt.Sprintf("{ name: %s, tag: %d, fields: [%s] }",
				bunStringLiteral(name), variant.Tag, strings.Join(fields, ", ")))
		}
		g.line(1, "{ name: %s, kind: \"union\", fields: [], methods: [], interfaces: [], variants: [%s] },",
			bunStringLiteral(union.ID), strings.Join(variants, ", "))
	}
	g.line(0, "];")
	g.line(0, "")
}

func (g *bunGenerator) emitDispatchTables() {
	g.line(0, "const SLICK_FUNCTIONS = {")
	for _, function := range g.core.Functions {
		if function.Receiver == "" {
			g.line(1, "%s: %s,", bunStringLiteral(function.ID), bunFunctionName(function.ID))
		}
	}
	g.line(0, "};")
	g.line(0, "")
	g.line(0, "const SLICK_METHODS = {")
	for _, function := range g.core.Functions {
		if function.Receiver == "" {
			continue
		}
		name, _ := coreDeclarationName(function.ID)
		g.line(1, "%s: %s,", bunStringLiteral(function.Receiver+"."+name), bunFunctionName(function.ID))
	}
	// Native resource methods have no Slick body, so using-scope cleanup and
	// interface-typed calls reach them through compiler-owned entry points. Only
	// linked families are dispatched, because only their modules are bundled.
	for _, class := range g.core.Classes {
		for _, method := range class.Methods {
			if method.Operation == "" {
				continue
			}
			native, ok := bunStdFunction(method.Operation)
			if !ok || !g.runtime.families[runtimeOperationRegistry[method.Operation].family] {
				continue
			}
			name, _ := coreDeclarationName(method.ID)
			g.line(1, "%s: (slick_context, slick_receiver, slick_arguments) => slick.%s(slick_context, [slick_receiver, ...slick_arguments]),",
				bunStringLiteral(class.ID+"."+name), native)
		}
	}
	g.line(0, "};")
	g.line(0, "")
	g.line(0, "const SLICK_CALLABLES = {")
	for _, function := range g.core.Functions {
		if function.Receiver != "" {
			continue
		}
		g.line(1, "%s: (slick_context, slick_captures, slick_arguments) => %s(slick_context, null, slick_arguments),",
			bunStringLiteral(function.ID), bunFunctionName(function.ID))
	}
	for _, lambda := range g.lambdas {
		g.line(1, "%s: %s,", bunStringLiteral(lambda.id), bunLambdaName(lambda.id))
	}
	g.line(0, "};")
	g.line(0, "")
	g.line(0, "const SLICK_OPERATIONS = {")
	for _, operation := range g.runtime.operations {
		native, ok := bunStdFunction(operation)
		if !ok {
			continue
		}
		g.line(1, "%s: slick.%s,", bunStringLiteral(string(operation)), native)
	}
	g.line(0, "};")
	g.line(0, "")
}

func (g *bunGenerator) function(function coreFunction) error {
	g.locals = make(map[string]string)
	g.line(0, "async function %s(slick_context, slick_self, slick_arguments) {", bunFunctionName(function.ID))
	g.line(1, "slick.slickCheckCancelled(slick_context);")
	if function.Receiver != "" {
		g.line(1, "let %s = slick_self;", g.declareLocal("self"))
	}
	for index, parameter := range function.Parameters {
		g.line(1, "let %s = slick_arguments[%d];", g.declareLocal(parameter.Name), index)
	}
	if err := g.block(function.Body, 1, "", true); err != nil {
		return fmt.Errorf("generate Bun function %s: %w", function.ID, err)
	}
	g.line(0, "}")
	return nil
}

func (g *bunGenerator) emitLambdas() error {
	// Lambdas discovered while generating bodies may themselves contain
	// lambdas, so the list is walked by index.
	for index := 0; index < len(g.lambdas); index++ {
		lambda := g.lambdas[index]
		if lambda.expression.Body == nil {
			return bunLoweringError(lambda.expression.Location, "lambda has no body")
		}
		g.locals = make(map[string]string)
		g.line(0, "async function %s(slick_context, slick_captures, slick_arguments) {", bunLambdaName(lambda.id))
		g.line(1, "slick.slickCheckCancelled(slick_context);")
		for captureIndex, capture := range lambda.expression.Captures {
			g.line(1, "let %s = slick_captures[%d];", g.declareLocal(capture.Name), captureIndex)
		}
		for parameterIndex, parameter := range lambda.expression.Parameters {
			g.line(1, "let %s = slick_arguments[%d];", g.declareLocal(parameter.Name), parameterIndex)
		}
		if err := g.block(*lambda.expression.Body, 1, "", true); err != nil {
			return err
		}
		g.line(0, "}")
		g.line(0, "")
	}
	return nil
}

// block emits statements. `returns` marks a block whose value is the enclosing
// function result; nested blocks assign into a temporary through `sink`.
func (g *bunGenerator) block(block coreBlock, level int, scope string, returns bool) error {
	return g.blockInto(block, level, scope, func(value string) {
		if returns {
			g.line(level, "return %s;", value)
		}
	})
}

func (g *bunGenerator) blockInto(block coreBlock, level int, scope string, sink func(string)) error {
	if block.StructuredTasks {
		return g.structuredBlock(block, level, sink)
	}
	return g.plainBlock(block, level, scope, sink)
}

func (g *bunGenerator) plainBlock(block coreBlock, level int, scope string, sink func(string)) error {
	for index, statement := range block.Statements {
		last := index == len(block.Statements)-1
		if last && statement.Kind == "expression" && statement.Value != nil {
			value, err := g.expression(*statement.Value, level, scope)
			if err != nil {
				return err
			}
			sink(value)
			return nil
		}
		if err := g.statement(statement, level, scope); err != nil {
			return err
		}
	}
	if block.Result != typeNever {
		// A block with no final expression still carries the declared result
		// conversion, so an implicit null becomes tagged absence when the
		// declaration is optional.
		implicit := "null"
		if block.ResultConversion != "" {
			implicit = fmt.Sprintf("slick.slickConvert(null, %s)", bunStringLiteral(block.ResultConversion))
		}
		sink(implicit)
	}
	return nil
}

// structuredBlock owns a task scope: every launched child is cancelled, joined,
// and terminated before the block exits on any path, and a surviving child
// failure is suppressed onto the primary failure.
func (g *bunGenerator) structuredBlock(block coreBlock, level int, sink func(string)) error {
	scope := fmt.Sprintf("slick_scope_%d", g.scopes)
	g.scopes++
	failure := g.nextTemporary()
	g.line(level, "const %s = new slick.SlickTaskScope(slick_context);", scope)
	g.line(level, "let %s = null;", failure)
	g.line(level, "try {")
	if err := g.plainBlock(block, level+1, scope, sink); err != nil {
		return err
	}
	g.line(level, "} catch (slick_error) {")
	g.line(level+1, "%s = slick.slickAsFailure(slick_error);", failure)
	g.line(level, "} finally {")
	g.line(level+1, "const slick_children = await %s.finish();", scope)
	g.line(level+1, "if (slick_children !== null) {")
	g.line(level+2, "%s = %s === null ? slick_children : slick.slickSuppress(%s, slick_children);", failure, failure, failure)
	g.line(level+1, "}")
	g.line(level+1, "if (%s !== null) throw %s;", failure, failure)
	g.line(level, "}")
	return nil
}

func (g *bunGenerator) statement(statement coreStatement, level int, scope string) error {
	value := func() (string, error) {
		if statement.Value == nil {
			return "", bunLoweringError(statement.Location, "%s statement has no value", statement.Kind)
		}
		return g.expression(*statement.Value, level, scope)
	}
	switch statement.Kind {
	case "bind":
		bound, err := value()
		if err != nil {
			return err
		}
		if len(statement.Bindings) == 1 {
			if statement.Bindings[0].Name == "_" {
				g.line(level, "void %s;", bound)
				return nil
			}
			g.line(level, "let %s = %s;", g.declareLocal(statement.Bindings[0].Name), bound)
			return nil
		}
		tuple := g.nextTemporary()
		g.line(level, "const %s = %s;", tuple, bound)
		for index, binding := range statement.Bindings {
			if binding.Name == "_" {
				continue
			}
			g.line(level, "let %s = slick.slickTupleItem(%s, %d);", g.declareLocal(binding.Name), tuple, index)
		}
		return nil
	case "assign":
		assigned, err := value()
		if err != nil {
			return err
		}
		g.line(level, "%s = %s;", g.localName(statement.Target), assigned)
		return nil
	case "task_launch":
		if scope == "" || len(statement.Bindings) != 1 || statement.Value == nil {
			return bunLoweringError(statement.Location, "task launch has no structured scope")
		}
		request, err := g.taskRequest(*statement.Value, level, scope)
		if err != nil {
			return err
		}
		g.line(level, "const %s = %s.launch(%s);", g.declareLocal(statement.Bindings[0].Name), scope, request)
		return nil
	case "loop":
		iterable, err := value()
		if err != nil {
			return err
		}
		if statement.Body == nil {
			return bunLoweringError(statement.Location, "loop has no body")
		}
		item := g.nextTemporary()
		previous := g.enterScope()
		g.line(level, "for (const %s of slick.slickIter(%s)) {", item, iterable)
		g.line(level+1, "slick.slickCheckCancelled(slick_context);")
		if len(statement.Bindings) == 1 {
			if statement.Bindings[0].Name != "_" {
				g.line(level+1, "let %s = %s;", g.declareLocal(statement.Bindings[0].Name), item)
			}
		} else {
			for index, binding := range statement.Bindings {
				if binding.Name == "_" {
					continue
				}
				g.line(level+1, "let %s = slick.slickTupleItem(%s, %d);", g.declareLocal(binding.Name), item, index)
			}
		}
		// A loop body's value is discarded, but its final expression must still
		// run: the sink evaluates it as a statement.
		discard := func(value string) {
			if value != "null" {
				g.line(level+1, "void %s;", value)
			}
		}
		if err := g.blockInto(*statement.Body, level+1, scope, discard); err != nil {
			return err
		}
		g.line(level, "}")
		g.leaveScope(previous)
		return nil
	case "break", "continue":
		g.line(level, "%s;", statement.Kind)
		return nil
	case "throw":
		thrown, err := value()
		if err != nil {
			return err
		}
		g.line(level, "throw slick.slickFailureFromValue(%s);", thrown)
		return nil
	case "return":
		returned, err := value()
		if err != nil {
			return err
		}
		g.line(level, "return %s;", returned)
		return nil
	case "expression":
		evaluated, err := value()
		if err != nil {
			return err
		}
		g.line(level, "void %s;", evaluated)
		return nil
	default:
		return bunLoweringError(statement.Location, "statement %s is not supported", statement.Kind)
	}
}

func (g *bunGenerator) expression(expression coreExpression, level int, scope string) (string, error) {
	raw, err := g.rawExpression(expression, level, scope)
	if err != nil {
		return "", err
	}
	for _, conversion := range []string{expression.Conversion, expression.ReadConversion} {
		if conversion != "" {
			raw = fmt.Sprintf("slick.slickConvert(%s, %s)", raw, bunStringLiteral(conversion))
		}
	}
	return raw, nil
}

func (g *bunGenerator) rawExpression(expression coreExpression, level int, scope string) (string, error) {
	child := func(value *coreExpression) (string, error) {
		if value == nil {
			return "", bunLoweringError(expression.Location, "%s expression has no child", expression.Kind)
		}
		return g.expression(*value, level, scope)
	}
	switch expression.Kind {
	case "literal":
		if expression.Literal == nil {
			return "", bunLoweringError(expression.Location, "literal has no value")
		}
		literal, err := g.literal(*expression.Literal)
		if err != nil {
			return "", bunLoweringError(expression.Location, "%v", err)
		}
		return literal, nil
	case "name":
		return g.nameExpression(expression), nil
	case "tuple", "array":
		values, err := g.evaluatedExpressions(expression.Elements, level, scope)
		if err != nil {
			return "", err
		}
		if expression.Kind == "array" {
			return "[" + strings.Join(values, ", ") + "]", nil
		}
		return "new slick.SlickTuple([" + strings.Join(values, ", ") + "])", nil
	case "map":
		entries := make([]string, 0, len(expression.Entries))
		for _, entry := range expression.Entries {
			key, err := g.evaluated(entry.Key, level, scope)
			if err != nil {
				return "", err
			}
			value, err := g.evaluated(entry.Value, level, scope)
			if err != nil {
				return "", err
			}
			entries = append(entries, fmt.Sprintf("[%s, %s]", key, value))
		}
		return fmt.Sprintf("slick.slickMap([%s])", strings.Join(entries, ", ")), nil
	case "range":
		left, err := g.evaluatedPointer(expression.Left, level, scope, expression)
		if err != nil {
			return "", err
		}
		right, err := g.evaluatedPointer(expression.Right, level, scope, expression)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("slick.slickRange(%s, %s)", left, right), nil
	case "template":
		text := g.nextTemporary()
		g.line(level, "let %s = \"\";", text)
		for _, part := range expression.Template {
			if part.Name == "" {
				g.line(level, "%s += %s;", text, bunStringLiteral(part.Text))
				continue
			}
			value := g.nameExpression(coreExpression{Name: part.Name, Declaration: part.Declaration})
			if part.ReadConversion != "" {
				value = fmt.Sprintf("slick.slickConvert(%s, %s)", value, bunStringLiteral(part.ReadConversion))
			}
			g.line(level, "%s += slick.slickFormat(%s);", text, value)
		}
		return text, nil
	case "object":
		values := make(map[string]string, len(expression.Fields))
		order := make([]string, 0, len(expression.Fields))
		for _, field := range expression.Fields {
			value, err := g.evaluated(field.Value, level, scope)
			if err != nil {
				return "", err
			}
			values[field.Name] = value
			order = append(order, field.Name)
		}
		// An object literal may omit an optional field; the value still carries
		// every declared field, initialized to tagged absence.
		fields := make([]string, 0, len(values))
		for _, field := range g.classes[expression.Declaration].Fields {
			value, ok := values[field.Name]
			if !ok {
				value = "slick.slickAbsent"
				if !strings.HasSuffix(field.Type, "?") {
					value = "null"
				}
			}
			delete(values, field.Name)
			fields = append(fields, fmt.Sprintf("[%s, %s]", bunStringLiteral(field.Name), value))
		}
		for _, name := range order {
			if value, ok := values[name]; ok {
				fields = append(fields, fmt.Sprintf("[%s, %s]", bunStringLiteral(name), value))
			}
		}
		return fmt.Sprintf("new slick.SlickObject(%s, new Map([%s]), null)",
			bunStringLiteral(expression.Declaration), strings.Join(fields, ", ")), nil
	case "lambda":
		id := fmt.Sprintf("lambda.%d", len(g.lambdas))
		g.lambdas = append(g.lambdas, bunLambda{id: id, expression: expression})
		captures := make([]string, 0, len(expression.Captures))
		for _, capture := range expression.Captures {
			captures = append(captures, g.localName(capture.Name))
		}
		return fmt.Sprintf("new slick.SlickCallable(%s, [%s])", bunStringLiteral(id), strings.Join(captures, ", ")), nil
	case "call":
		return g.call(expression, level, scope)
	case "task_await":
		if scope == "" {
			return "", bunLoweringError(expression.Location, "await has no structured task scope")
		}
		return fmt.Sprintf("(await %s.awaitTask(%s))", scope, g.localName(expression.Name)), nil
	case "unary":
		value, err := child(expression.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("slick.slickUnary(%s, %s)", bunStringLiteral(expression.Operator), value), nil
	case "binary":
		return g.binaryExpression(expression, level, scope)
	case "branch":
		return g.branchExpression(expression, level, scope)
	case "catch":
		return g.catchExpression(expression, level, scope)
	case "result":
		value, err := child(expression.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("new slick.SlickResult(%t, %s)", expression.ResultVariant == "ok", value), nil
	case "propagate":
		value, err := g.evaluatedPointer(expression.Value, level, scope, expression)
		if err != nil {
			return "", err
		}
		propagated := g.nextTemporary()
		g.line(level, "const %s = slick.slickPropagateFailure(%s);", propagated, value)
		g.line(level, "if (%s !== null) return %s;", propagated, propagated)
		return fmt.Sprintf("%s.value", value), nil
	case "using":
		return g.usingExpression(expression, level, scope)
	case "match":
		return g.matchExpression(expression, level, scope)
	default:
		return "", bunLoweringError(expression.Location, "expression %s is not supported", expression.Kind)
	}
}

func (g *bunGenerator) nameExpression(expression coreExpression) string {
	if _, ok := g.constants[expression.Declaration]; ok {
		return fmt.Sprintf("%s()", bunConstantName(expression.Declaration))
	}
	if variant, ok := g.variants[expression.Declaration]; ok {
		return fmt.Sprintf("new slick.SlickUnion(%s, %s, %d, [])",
			bunStringLiteral(variant.union), bunStringLiteral(variant.name), variant.tag)
	}
	if _, ok := g.functions[expression.Declaration]; ok {
		return fmt.Sprintf("new slick.SlickCallable(%s, [])", bunStringLiteral(expression.Declaration))
	}
	parts := strings.Split(expression.Name, ".")
	if len(parts) == 0 || parts[0] == "" {
		return `slick.slickField(null, "")`
	}
	if len(parts) == 1 {
		return g.localName(parts[0])
	}
	path := make([]string, 0, len(parts)-1)
	for _, part := range parts[1:] {
		path = append(path, bunStringLiteral(part))
	}
	return fmt.Sprintf("slick.slickPath(%s, [%s])", g.localName(parts[0]), strings.Join(path, ", "))
}

func (g *bunGenerator) binaryExpression(expression coreExpression, level int, scope string) (string, error) {
	if expression.Left == nil || expression.Right == nil {
		return "", bunLoweringError(expression.Location, "binary expression has no operand")
	}
	left, err := g.evaluated(*expression.Left, level, scope)
	if err != nil {
		return "", err
	}
	if expression.ShortCircuit || expression.Operator == "&&" || expression.Operator == "||" {
		result := g.nextTemporary()
		short := "false"
		condition := fmt.Sprintf("slick.slickTruth(%s)", left)
		if expression.Operator == "||" {
			short = "true"
		} else {
			condition = "!" + condition
		}
		g.line(level, "let %s = %s;", result, short)
		g.line(level, "if (!(%s)) {", condition)
		right, err := g.expression(*expression.Right, level+1, scope)
		if err != nil {
			return "", err
		}
		g.line(level+1, "%s = %s;", result, right)
		g.line(level, "}")
		return result, nil
	}
	right, err := g.evaluated(*expression.Right, level, scope)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("slick.slickBinary(%s, %s, %s)", bunStringLiteral(expression.Operator), left, right), nil
}

func (g *bunGenerator) branchExpression(expression coreExpression, level int, scope string) (string, error) {
	if expression.Value == nil || expression.Body == nil || expression.Alternate == nil {
		return "", bunLoweringError(expression.Location, "branch has a missing arm")
	}
	condition, err := g.evaluated(*expression.Value, level, scope)
	if err != nil {
		return "", err
	}
	result := g.nextTemporary()
	g.line(level, "let %s = null;", result)
	g.line(level, "if (slick.slickTruth(%s)) {", condition)
	sink := func(value string) { g.line(level+1, "%s = %s;", result, value) }
	consequent := g.enterScope()
	if err := g.blockInto(*expression.Body, level+1, scope, sink); err != nil {
		return "", err
	}
	g.leaveScope(consequent)
	g.line(level, "} else {")
	alternate := g.enterScope()
	if err := g.blockInto(*expression.Alternate, level+1, scope, sink); err != nil {
		return "", err
	}
	g.leaveScope(alternate)
	g.line(level, "}")
	return result, nil
}

// catchExpression converts a declared Slick failure into a value. Cancellation
// and host failures are never catchable, so they keep propagating.
func (g *bunGenerator) catchExpression(expression coreExpression, level int, scope string) (string, error) {
	if expression.Value == nil {
		return "", bunLoweringError(expression.Location, "catch has no value")
	}
	result := g.nextTemporary()
	failure := g.nextTemporary()
	g.line(level, "let %s = null;", result)
	g.line(level, "try {")
	value, err := g.expression(*expression.Value, level+1, scope)
	if err != nil {
		return "", err
	}
	g.line(level+1, "%s = %s;", result, value)
	g.line(level, "} catch (slick_error) {")
	g.line(level+1, "const %s = slick.slickAsFailure(slick_error);", failure)
	for index, arm := range expression.Arms {
		prefix := "if"
		if index > 0 {
			prefix = "} else if"
		}
		g.line(level+1, "%s (slick.slickMatchFailure(%s, %s)) {", prefix, failure, bunStringLiteral(arm.Pattern))
		previous := g.enterScope()
		for _, binding := range arm.Bindings {
			if binding.Name != "_" {
				g.line(level+2, "let %s = slick.slickFailureValue(%s);", g.declareLocal(binding.Name), failure)
			}
		}
		armValue, err := g.expression(arm.Value, level+2, scope)
		if err != nil {
			return "", err
		}
		g.line(level+2, "%s = %s;", result, armValue)
		g.leaveScope(previous)
	}
	if len(expression.Arms) == 0 {
		g.line(level+1, "throw %s;", failure)
	} else {
		g.line(level+1, "} else {")
		g.line(level+2, "throw %s;", failure)
		g.line(level+1, "}")
	}
	g.line(level, "}")
	return result, nil
}

// usingExpression runs cleanup on every exit path, including return, break, and
// continue, and suppresses a cleanup failure onto an in-flight primary failure.
func (g *bunGenerator) usingExpression(expression coreExpression, level int, scope string) (string, error) {
	if expression.Value == nil || expression.Body == nil || len(expression.Bindings) != 1 {
		return "", bunLoweringError(expression.Location, "invalid using expression")
	}
	initializer, err := g.evaluated(*expression.Value, level, scope)
	if err != nil {
		return "", err
	}
	result := g.nextTemporary()
	failure := g.nextTemporary()
	g.line(level, "let %s = null;", result)
	g.line(level, "let %s = null;", failure)
	g.line(level, "try {")
	previous := g.enterScope()
	g.line(level+1, "let %s = %s;", g.declareLocal(expression.Bindings[0].Name), initializer)
	sink := func(value string) { g.line(level+1, "%s = %s;", result, value) }
	if err := g.blockInto(*expression.Body, level+1, scope, sink); err != nil {
		return "", err
	}
	g.leaveScope(previous)
	g.line(level, "} catch (slick_error) {")
	g.line(level+1, "%s = slick.slickAsFailure(slick_error);", failure)
	g.line(level, "} finally {")
	g.line(level+1, "try {")
	// Cleanup runs with cancellation detached, so a cancelled scope still closes
	// its resource.
	g.line(level+2, "await slick.slickCallMethod(slick.slickCleanupContext(slick_context), %s, \"Close\", []);", initializer)
	g.line(level+1, "} catch (slick_cleanup_error) {")
	g.line(level+2, "const slick_cleanup = slick.slickAsFailure(slick_cleanup_error);")
	g.line(level+2, "%s = %s === null ? slick_cleanup : slick.slickSuppress(%s, slick_cleanup);", failure, failure, failure)
	g.line(level+1, "}")
	g.line(level+1, "if (%s !== null) throw %s;", failure, failure)
	g.line(level, "}")
	return result, nil
}

func (g *bunGenerator) matchExpression(expression coreExpression, level int, scope string) (string, error) {
	if expression.Value == nil {
		return "", bunLoweringError(expression.Location, "match has no value")
	}
	scrutinee, err := g.evaluated(*expression.Value, level, scope)
	if err != nil {
		return "", err
	}
	result := g.nextTemporary()
	g.line(level, "let %s = null;", result)
	// Payload storage is declared ahead of the chain: a binding declared inside
	// one arm is not in scope for the next arm's test.
	payloads := make([]string, len(expression.Arms))
	conditions := make([]string, len(expression.Arms))
	for index, arm := range expression.Arms {
		conditions[index] = "true"
		switch arm.Pattern {
		case "variant":
			variant, _ := coreDeclarationName(arm.Variant)
			payloads[index] = g.nextTemporary()
			conditions[index] = fmt.Sprintf("(%s = slick.slickUnionPayload(%s, %s)) !== null",
				payloads[index], scrutinee, bunStringLiteral(variant))
		case "Ok", "Err":
			payloads[index] = g.nextTemporary()
			conditions[index] = fmt.Sprintf("(%s = slick.slickResultPayload(%s, %t)) !== null",
				payloads[index], scrutinee, arm.Pattern == "Ok")
		}
		if payloads[index] != "" {
			g.line(level, "let %s = null;", payloads[index])
		}
	}
	for index, arm := range expression.Arms {
		prefix := "if"
		if index > 0 {
			prefix = "} else if"
		}
		payload := payloads[index]
		g.line(level, "%s (%s) {", prefix, conditions[index])
		previous := g.enterScope()
		for bindingIndex, binding := range arm.Bindings {
			if binding.Name == "_" {
				continue
			}
			switch {
			case arm.Pattern == "variant":
				g.line(level+1, "let %s = %d < %s.length ? %s[%d] : null;",
					g.declareLocal(binding.Name), bindingIndex, payload, payload, bindingIndex)
			case payload != "":
				g.line(level+1, "let %s = %s.value;", g.declareLocal(binding.Name), payload)
			default:
				g.line(level+1, "let %s = %s;", g.declareLocal(binding.Name), scrutinee)
			}
		}
		armValue, err := g.expression(arm.Value, level+1, scope)
		if err != nil {
			return "", err
		}
		g.line(level+1, "%s = %s;", result, armValue)
		g.leaveScope(previous)
	}
	if len(expression.Arms) == 0 {
		g.line(level, `throw slick.SlickFailure.host("non-exhaustive match");`)
		return result, nil
	}
	g.line(level, "} else {")
	g.line(level+1, `throw slick.SlickFailure.host("non-exhaustive match");`)
	g.line(level, "}")
	return result, nil
}

func (g *bunGenerator) call(expression coreExpression, level int, scope string) (string, error) {
	if strings.HasPrefix(expression.Declaration, "core.") {
		return g.coreCall(expression, level, scope)
	}
	if expression.Operation != "" {
		return g.standardCall(expression, level, scope)
	}
	if variant, ok := g.variants[expression.Declaration]; ok {
		values, err := g.evaluatedExpressions(expression.Arguments, level, scope)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("new slick.SlickUnion(%s, %s, %d, [%s])",
			bunStringLiteral(variant.union), bunStringLiteral(variant.name), variant.tag, strings.Join(values, ", ")), nil
	}
	// An error class doubles as a shorthand constructor whose single argument is
	// only the failure message: no declared field is set, so the text travels in
	// the value's failure metadata instead.
	if g.errorClasses[expression.Declaration] {
		values, err := g.evaluatedExpressions(expression.Arguments, level, scope)
		if err != nil {
			return "", err
		}
		message := `""`
		if len(values) > 0 {
			message = fmt.Sprintf("slick.slickFormat(%s)", values[0])
		}
		return fmt.Sprintf("new slick.SlickObject(%s, new Map(), null, %s)",
			bunStringLiteral(expression.Declaration), message), nil
	}
	target, err := g.callTarget(expression, level, scope)
	if err != nil {
		return "", err
	}
	arguments, err := g.evaluatedExpressions(expression.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	switch {
	case target.callee != "":
		return fmt.Sprintf("(await slick.slickCallCallable(slick_context, %s, [%s]))",
			target.callee, strings.Join(arguments, ", ")), nil
	case target.receiver != "":
		return fmt.Sprintf("(await slick.slickCallMethod(slick_context, %s, %s, [%s]))",
			target.receiver, bunStringLiteral(expression.Declaration), strings.Join(arguments, ", ")), nil
	default:
		if _, ok := g.functions[expression.Declaration]; !ok {
			return "", bunLoweringError(expression.Location, "unknown function %s", expression.Declaration)
		}
		return fmt.Sprintf("(await %s(slick_context, null, [%s]))",
			bunFunctionName(expression.Declaration), strings.Join(arguments, ", ")), nil
	}
}

type bunCallTarget struct {
	callee   string
	receiver string
}

func (g *bunGenerator) callTarget(expression coreExpression, level int, scope string) (bunCallTarget, error) {
	if expression.Value != nil {
		callee, err := g.evaluated(*expression.Value, level, scope)
		if err != nil {
			return bunCallTarget{}, err
		}
		return bunCallTarget{callee: callee}, nil
	}
	if expression.Receiver != nil {
		receiver, err := g.evaluated(*expression.Receiver, level, scope)
		if err != nil {
			return bunCallTarget{}, err
		}
		return bunCallTarget{receiver: receiver}, nil
	}
	if expression.Declaration == "" {
		return bunCallTarget{}, bunLoweringError(expression.Location, "call has no target")
	}
	return bunCallTarget{}, nil
}

func (g *bunGenerator) coreCall(expression coreExpression, level int, scope string) (string, error) {
	values, err := g.evaluatedExpressions(expression.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	switch expression.Declaration {
	case "core.enumerate":
		if len(values) != 1 {
			return "", bunLoweringError(expression.Location, "enumerate expects one argument")
		}
		return fmt.Sprintf("new slick.SlickEnumerate(%s)", values[0]), nil
	case "core.zip":
		return fmt.Sprintf("new slick.SlickZip([%s])", strings.Join(values, ", ")), nil
	case "core.unwrap":
		if len(values) != 1 {
			return "", bunLoweringError(expression.Location, "unwrap expects one argument")
		}
		return fmt.Sprintf("slick.slickUnwrap(%s)", values[0]), nil
	default:
		return "", bunLoweringError(expression.Location, "compiler operation %s is not supported", expression.Declaration)
	}
}

// standardCall lowers one compiler-owned standard-library operation. A method
// operation receives its receiver as the first argument, then the declared
// parameters, then the resolved type arguments, so every family implements one
// uniform entry point.
func (g *bunGenerator) standardCall(expression coreExpression, level int, scope string) (string, error) {
	function, ok := bunStdFunction(expression.Operation)
	if !ok {
		return "", bunLoweringError(expression.Location, "standard-library operation %s is not supported", expression.Operation)
	}
	values := make([]string, 0, len(expression.Arguments)+1)
	if expression.Receiver != nil {
		receiver, err := g.evaluated(*expression.Receiver, level, scope)
		if err != nil {
			return "", err
		}
		values = append(values, receiver)
	}
	arguments, err := g.evaluatedExpressions(expression.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	values = append(values, arguments...)
	for _, typeArgument := range expression.TypeArguments {
		values = append(values, bunStringLiteral(typeArgument))
	}
	return fmt.Sprintf("(await slick.%s(slick_context, [%s]))", function, strings.Join(values, ", ")), nil
}

// taskRequest materializes a launch request. Only task-safe values reach the
// worker; the runtime rejects buffers and host resources.
func (g *bunGenerator) taskRequest(call coreExpression, level int, scope string) (string, error) {
	if call.Kind != "call" || strings.HasPrefix(call.Declaration, "core.") {
		return "", bunLoweringError(call.Location, "task launch target is not a call")
	}
	if call.Operation != "" {
		if _, ok := bunStdFunction(call.Operation); !ok {
			return "", bunLoweringError(call.Location, "standard-library operation %s is not supported", call.Operation)
		}
	}
	target, err := g.callTarget(call, level, scope)
	if err != nil {
		return "", err
	}
	arguments, err := g.evaluatedExpressions(call.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	if call.Operation != "" {
		// A launched standard-library operation runs its compiler-owned entry
		// point in the worker, receiving the same receiver-first arguments.
		values := arguments
		if target.receiver != "" {
			values = append([]string{target.receiver}, arguments...)
		}
		for _, typeArgument := range call.TypeArguments {
			values = append(values, bunStringLiteral(typeArgument))
		}
		return fmt.Sprintf("{ kind: \"operation\", target: %s, arguments: [%s] }",
			bunStringLiteral(string(call.Operation)), strings.Join(values, ", ")), nil
	}
	switch {
	case target.callee != "":
		return fmt.Sprintf("{ kind: \"callable\", target: %s, callee: %s, arguments: [%s] }",
			bunStringLiteral(call.Declaration), target.callee, strings.Join(arguments, ", ")), nil
	case target.receiver != "":
		return fmt.Sprintf("{ kind: \"method\", target: %s, receiver: %s, arguments: [%s] }",
			bunStringLiteral(call.Declaration), target.receiver, strings.Join(arguments, ", ")), nil
	default:
		if _, ok := g.functions[call.Declaration]; !ok {
			return "", bunLoweringError(call.Location, "unknown function %s", call.Declaration)
		}
		return fmt.Sprintf("{ kind: \"function\", target: %s, arguments: [%s] }",
			bunStringLiteral(call.Declaration), strings.Join(arguments, ", ")), nil
	}
}

// evaluated materializes one expression into a named constant so Core's
// left-to-right, exactly-once evaluation order survives generation.
func (g *bunGenerator) evaluated(expression coreExpression, level int, scope string) (string, error) {
	value, err := g.expression(expression, level, scope)
	if err != nil {
		return "", err
	}
	name := g.nextTemporary()
	g.line(level, "const %s = %s;", name, value)
	return name, nil
}

func (g *bunGenerator) evaluatedPointer(expression *coreExpression, level int, scope string, parent coreExpression) (string, error) {
	if expression == nil {
		return "", bunLoweringError(parent.Location, "%s expression has no child", parent.Kind)
	}
	return g.evaluated(*expression, level, scope)
}

func (g *bunGenerator) evaluatedExpressions(expressions []coreExpression, level int, scope string) ([]string, error) {
	values := make([]string, 0, len(expressions))
	for _, expression := range expressions {
		value, err := g.evaluated(expression, level, scope)
		if err != nil {
			return nil, err
		}
		values = append(values, value)
	}
	return values, nil
}

func (g *bunGenerator) literal(literal coreLiteral) (string, error) {
	switch literal.Kind {
	case "null":
		return "null", nil
	case "bool":
		return strconv.FormatBool(literal.Boolean), nil
	case "int":
		return strconv.FormatInt(literal.Integer, 10) + "n", nil
	case "float":
		switch {
		case math.IsNaN(literal.Float):
			return "NaN", nil
		case math.IsInf(literal.Float, 1):
			return "Infinity", nil
		case math.IsInf(literal.Float, -1):
			return "-Infinity", nil
		default:
			return strconv.FormatFloat(literal.Float, 'g', -1, 64), nil
		}
	case "string":
		return bunStringLiteral(literal.Text), nil
	case "union":
		variant, ok := g.variants[literal.Variant]
		if !ok {
			return "", fmt.Errorf("unknown Core union literal %q", literal.Variant)
		}
		return fmt.Sprintf("new slick.SlickUnion(%s, %s, %d, [])",
			bunStringLiteral(variant.union), bunStringLiteral(variant.name), variant.tag), nil
	default:
		return "", fmt.Errorf("literal kind %s is not supported", literal.Kind)
	}
}

func (g *bunGenerator) nextTemporary() string {
	name := fmt.Sprintf("slick_tmp_%d", g.temporary)
	g.temporary++
	return name
}

// Slick allows a block to rebind a name its parent already bound, which is not
// a legal JavaScript redeclaration, so every binding gets a unique storage name
// and reads resolve through the innermost lexical scope.
func (g *bunGenerator) declareLocal(name string) string {
	local := fmt.Sprintf("%s_%d", bunLocalName(name), g.temporary)
	g.temporary++
	g.locals[name] = local
	return local
}

func (g *bunGenerator) localName(name string) string {
	if local, ok := g.locals[name]; ok {
		return local
	}
	return bunLocalName(name)
}

func (g *bunGenerator) enterScope() map[string]string {
	previous := g.locals
	scoped := make(map[string]string, len(previous))
	for name, local := range previous {
		scoped[name] = local
	}
	g.locals = scoped
	return previous
}

func (g *bunGenerator) leaveScope(previous map[string]string) {
	g.locals = previous
}

func (g *bunGenerator) line(level int, format string, arguments ...any) {
	if format == "" {
		g.output.WriteByte('\n')
		return
	}
	g.output.WriteString(strings.Repeat("  ", level))
	fmt.Fprintf(&g.output, format, arguments...)
	g.output.WriteByte('\n')
}

func bunStringLiteral(value string) string {
	var output strings.Builder
	output.WriteByte('"')
	for _, r := range value {
		switch r {
		case '\\':
			output.WriteString("\\\\")
		case '"':
			output.WriteString("\\\"")
		case '\b':
			output.WriteString("\\b")
		case '\f':
			output.WriteString("\\f")
		case '\n':
			output.WriteString("\\n")
		case '\r':
			output.WriteString("\\r")
		case '\t':
			output.WriteString("\\t")
		default:
			switch {
			case r >= 0x20 && r <= 0x7e:
				output.WriteRune(r)
			case r <= 0xffff:
				fmt.Fprintf(&output, "\\u%04x", r)
			default:
				value := r - 0x10000
				fmt.Fprintf(&output, "\\u%04x\\u%04x", 0xd800+(value>>10), 0xdc00+(value&0x3ff))
			}
		}
	}
	output.WriteByte('"')
	return output.String()
}

func bunFunctionName(name string) string { return "slick_fn_" + hex.EncodeToString([]byte(name)) }
func bunLambdaName(name string) string   { return "slick_lambda_" + hex.EncodeToString([]byte(name)) }
func bunConstantName(name string) string {
	return "SLICK_CONST_" + strings.ToUpper(hex.EncodeToString([]byte(name)))
}
func bunLocalName(name string) string { return "slick_local_" + hex.EncodeToString([]byte(name)) }
