package compiler

import (
	"encoding/hex"
	"fmt"
	"math"
	"strconv"
	"strings"
	"unicode/utf8"
)

func validateRustCore(core coreProgram, runtime backendRuntimeInputs) error {
	if err := validateLanguageCore(core, runtime, "Rust", func(operation runtimeOperationID) bool {
		_, ok := rustStdFunction(operation)
		return ok
	}); err != nil {
		return err
	}
	for _, function := range core.Functions {
		if function.ID != "root.main" {
			continue
		}
		// A command-line main takes the argument vector or nothing at all.
		if len(function.Parameters) > 1 ||
			(len(function.Parameters) == 1 && function.Parameters[0].Type != "string[]") {
			return rustLoweringError(function.Location, "root.main must accept no parameters or one string[] parameter")
		}
	}
	return nil
}

func rustLoweringError(location coreLocation, format string, arguments ...any) error {
	return backendLoweringError("Rust", location, format, arguments...)
}

func generateRust(core coreProgram) (string, error) {
	runtime, err := runtimeInputsForCore(core)
	if err != nil {
		return "", err
	}
	if err := validateRustCore(core, runtime); err != nil {
		return "", err
	}
	generator := newRustGenerator(core)
	generator.runtime = runtime
	return generator.generate()
}

type rustLambda struct {
	id         string
	expression coreExpression
}

type rustGenerator struct {
	core      coreProgram
	functions map[string]coreFunction
	constants map[string]coreConstant
	variants  map[string]struct {
		union string
		name  string
		tag   int
	}
	classes      map[string]coreClass
	errorClasses map[string]bool
	lambdas      []rustLambda
	runtime      backendRuntimeInputs
	temporary    int
	scope        int
}

func newRustGenerator(core coreProgram) *rustGenerator {
	generator := &rustGenerator{
		core: core, functions: make(map[string]coreFunction, len(core.Functions)),
		constants: make(map[string]coreConstant, len(core.Constants)),
		variants: make(map[string]struct {
			union string
			name  string
			tag   int
		}),
		classes:      make(map[string]coreClass, len(core.Classes)),
		errorClasses: make(map[string]bool),
	}
	for _, function := range core.Functions {
		generator.functions[function.ID] = function
	}
	for _, constant := range core.Constants {
		generator.constants[constant.ID] = constant
	}
	for _, union := range core.Unions {
		for _, variant := range union.Variants {
			name, _ := coreDeclarationName(variant.ID)
			generator.variants[variant.ID] = struct {
				union string
				name  string
				tag   int
			}{union: union.ID, name: name, tag: variant.Tag}
		}
	}
	for _, class := range core.Classes {
		generator.classes[class.ID] = class
		if class.Error {
			generator.errorClasses[class.ID] = true
		}
	}
	return generator
}

func (g *rustGenerator) generate() (string, error) {
	var output strings.Builder
	output.WriteString("// Generated by Slick. Compiler-owned Rust runtime ABI 1.\n")
	output.WriteString(rustRuntimeModule)
	if len(g.runtime.families) > 0 {
		output.WriteString(rustStdCoreModule)
		output.WriteString(rustStdModules(g.runtime))
	}
	g.emitTypeDescriptors(&output)
	for _, constant := range g.core.Constants {
		literal, err := g.literal(constant.Value)
		if err != nil {
			return "", rustLoweringError(constant.Location, "constant %s: %v", constant.ID, err)
		}
		fmt.Fprintf(&output, "fn %s() -> SlickValue { %s }\n", rustConstantName(constant.ID), literal)
	}
	if len(g.core.Constants) > 0 {
		output.WriteByte('\n')
	}
	for _, function := range g.core.Functions {
		generated, err := g.function(function)
		if err != nil {
			return "", err
		}
		output.WriteString(generated)
		output.WriteByte('\n')
	}
	callable, err := g.callableDispatcher()
	if err != nil {
		return "", err
	}
	output.WriteString(callable)
	output.WriteByte('\n')
	output.WriteString(g.methodDispatcher())
	output.WriteByte('\n')
	output.WriteString(g.mainFunction())
	return output.String(), nil
}

// emitTypeDescriptors publishes each declaration's shape, including the JSON
// name and declared type of every field, so descriptor-driven runtime behavior
// such as typed JSON never needs host reflection.
func (g *rustGenerator) emitTypeDescriptors(output *strings.Builder) {
	field := func(name, jsonName, typ string) string {
		if jsonName == "" {
			jsonName = name
		}
		return fmt.Sprintf("SlickFieldDescriptor { name: %s, json_name: %s, typ: %s }",
			rustStringLiteral(name), rustStringLiteral(jsonName), rustStringLiteral(typ))
	}
	output.WriteString("static SLICK_TYPES: &[SlickTypeDescriptor] = &[\n")
	for _, class := range g.core.Classes {
		fields := make([]string, 0, len(class.Fields))
		for _, declared := range class.Fields {
			fields = append(fields, field(declared.Name, declared.JSONName, declared.Type))
		}
		methods := make([]string, 0, len(class.Methods))
		for _, method := range class.Methods {
			name, _ := coreDeclarationName(method.ID)
			methods = append(methods, rustStringLiteral(name))
		}
		interfaces := make([]string, 0, len(class.Interfaces))
		for _, iface := range class.Interfaces {
			interfaces = append(interfaces, rustStringLiteral(iface))
		}
		fmt.Fprintf(output, "    SlickTypeDescriptor { name: %s, kind: \"class\", fields: &[%s], methods: &[%s], interfaces: &[%s], variants: &[] },\n",
			rustStringLiteral(class.ID), strings.Join(fields, ", "), strings.Join(methods, ", "), strings.Join(interfaces, ", "))
	}
	for _, iface := range g.core.Interfaces {
		methods := make([]string, 0, len(iface.Methods))
		for _, method := range iface.Methods {
			name, _ := coreDeclarationName(method.ID)
			methods = append(methods, rustStringLiteral(name))
		}
		fmt.Fprintf(output, "    SlickTypeDescriptor { name: %s, kind: \"interface\", fields: &[], methods: &[%s], interfaces: &[], variants: &[] },\n",
			rustStringLiteral(iface.ID), strings.Join(methods, ", "))
	}
	for _, union := range g.core.Unions {
		variants := make([]string, 0, len(union.Variants))
		for _, variant := range union.Variants {
			name, _ := coreDeclarationName(variant.ID)
			fields := make([]string, 0, len(variant.Fields))
			for _, declared := range variant.Fields {
				fields = append(fields, field(declared.Name, declared.JSONName, declared.Type))
			}
			variants = append(variants, fmt.Sprintf("SlickVariantDescriptor { name: %s, tag: %d, fields: &[%s] }",
				rustStringLiteral(name), variant.Tag, strings.Join(fields, ", ")))
		}
		fmt.Fprintf(output, "    SlickTypeDescriptor { name: %s, kind: \"union\", fields: &[], methods: &[], interfaces: &[], variants: &[%s] },\n",
			rustStringLiteral(union.ID), strings.Join(variants, ", "))
	}
	output.WriteString("];\n\n")
}

func (g *rustGenerator) function(function coreFunction) (string, error) {
	var output strings.Builder
	fmt.Fprintf(&output, "fn %s(slick_context: &SlickContext, slick_self: Option<SlickValue>, slick_arguments: Vec<SlickValue>) -> SlickOutcome {\n", rustFunctionName(function.ID))
	output.WriteString("    if let Some(outcome) = slick_cancelled(slick_context) { return outcome; }\n")
	if function.Receiver != "" {
		output.WriteString("    let Some(mut slick_local_73656c66) = slick_self else { return SlickOutcome::Throw(SlickFailure::host(\"method receiver is absent\")); };\n")
	} else {
		output.WriteString("    let _ = slick_self;\n")
	}
	for index, parameter := range function.Parameters {
		fmt.Fprintf(&output, "    let Some(mut %s) = slick_arguments.get(%d).cloned() else { return SlickOutcome::Throw(SlickFailure::host(\"missing function argument\")); };\n",
			rustLocalName(parameter.Name), index)
	}
	body, err := g.block(function.Body, 1, "")
	if err != nil {
		return "", fmt.Errorf("generate Rust function %s: %w", function.ID, err)
	}
	fmt.Fprintf(&output, "    slick_finish_function(%s)\n", body)
	output.WriteString("}\n")
	return output.String(), nil
}

func (g *rustGenerator) block(block coreBlock, level int, inheritedScope string) (string, error) {
	scope := inheritedScope
	structured := block.StructuredTasks
	if structured {
		scope = fmt.Sprintf("slick_scope_%d", g.scope)
		g.scope++
	}
	var body strings.Builder
	body.WriteString("(|| -> SlickOutcome {\n")
	for index, statement := range block.Statements {
		last := index == len(block.Statements)-1
		generated, err := g.statement(statement, level+2, last, scope)
		if err != nil {
			return "", err
		}
		body.WriteString(generated)
	}
	if len(block.Statements) == 0 || block.Statements[len(block.Statements)-1].Kind != "expression" {
		fmt.Fprintf(&body, "%sSlickOutcome::Value(SlickValue::Null)\n", rustIndent(level+2))
	}
	fmt.Fprintf(&body, "%s})()", rustIndent(level+1))
	if !structured {
		return body.String(), nil
	}
	var output strings.Builder
	output.WriteString("{\n")
	fmt.Fprintf(&output, "%slet mut %s = SlickTaskScope::new(slick_context);\n", rustIndent(level+1), scope)
	fmt.Fprintf(&output, "%slet slick_scope_outcome = %s;\n", rustIndent(level+1), body.String())
	fmt.Fprintf(&output, "%s%s.finish(slick_scope_outcome)\n", rustIndent(level+1), scope)
	fmt.Fprintf(&output, "%s}", rustIndent(level))
	return output.String(), nil
}

func (g *rustGenerator) statement(statement coreStatement, level int, last bool, scope string) (string, error) {
	indent := rustIndent(level)
	var output strings.Builder
	expression := func() (string, error) {
		if statement.Value == nil {
			return "", rustLoweringError(statement.Location, "%s statement has no value", statement.Kind)
		}
		return g.expression(*statement.Value, level, scope)
	}
	switch statement.Kind {
	case "bind":
		value, err := expression()
		if err != nil {
			return "", err
		}
		if len(statement.Bindings) == 1 {
			binding := statement.Bindings[0]
			if binding.Name == "_" {
				fmt.Fprintf(&output, "%slet _ = slick_value!(%s);\n", indent, value)
			} else {
				fmt.Fprintf(&output, "%slet mut %s = slick_value!(%s);\n", indent, rustLocalName(binding.Name), value)
			}
			break
		}
		tuple := g.nextTemporary()
		fmt.Fprintf(&output, "%slet %s = slick_value!(%s);\n", indent, tuple, value)
		for index, binding := range statement.Bindings {
			if binding.Name == "_" {
				continue
			}
			fmt.Fprintf(&output, "%slet mut %s = slick_tuple_item(&%s, %d);\n", indent, rustLocalName(binding.Name), tuple, index)
		}
	case "task_launch":
		if scope == "" || len(statement.Bindings) != 1 || statement.Value == nil {
			return "", rustLoweringError(statement.Location, "task launch has no structured scope")
		}
		launch, err := g.taskLaunch(*statement.Value, level, scope)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "%slet mut %s = %s;\n", indent, rustLocalName(statement.Bindings[0].Name), launch)
	case "assign":
		value, err := expression()
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "%s%s = slick_value!(%s);\n", indent, rustLocalName(statement.Target), value)
	case "loop":
		value, err := expression()
		if err != nil {
			return "", err
		}
		iterable := g.nextTemporary()
		fmt.Fprintf(&output, "%slet %s = slick_value!(%s);\n", indent, iterable, value)
		fmt.Fprintf(&output, "%slet Ok(slick_items) = slick_iter(%s) else { return SlickOutcome::Throw(SlickFailure::host(\"value is not iterable\")); };\n", indent, iterable)
		output.WriteString(indent + "for slick_item in slick_items {\n")
		fmt.Fprintf(&output, "%sif let Some(outcome) = slick_cancelled(slick_context) { return outcome; }\n", rustIndent(level+1))
		if len(statement.Bindings) == 1 {
			if statement.Bindings[0].Name != "_" {
				fmt.Fprintf(&output, "%slet mut %s = slick_item;\n", rustIndent(level+1), rustLocalName(statement.Bindings[0].Name))
			}
		} else {
			for index, binding := range statement.Bindings {
				if binding.Name != "_" {
					fmt.Fprintf(&output, "%slet mut %s = slick_tuple_item(&slick_item, %d);\n", rustIndent(level+1), rustLocalName(binding.Name), index)
				}
			}
		}
		if statement.Body == nil {
			return "", rustLoweringError(statement.Location, "loop has no body")
		}
		body, err := g.block(*statement.Body, level+1, scope)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "%smatch %s {\n", rustIndent(level+1), body)
		fmt.Fprintf(&output, "%sSlickOutcome::Value(_) => {},\n", rustIndent(level+2))
		fmt.Fprintf(&output, "%sSlickOutcome::Break => break,\n", rustIndent(level+2))
		fmt.Fprintf(&output, "%sSlickOutcome::Continue => continue,\n", rustIndent(level+2))
		fmt.Fprintf(&output, "%soutcome => return outcome,\n", rustIndent(level+2))
		fmt.Fprintf(&output, "%s}\n%s}\n", rustIndent(level+1), indent)
	case "break", "continue":
		name := "Break"
		if statement.Kind == "continue" {
			name = "Continue"
		}
		fmt.Fprintf(&output, "%sreturn SlickOutcome::%s;\n", indent, name)
	case "throw":
		value, err := expression()
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "%sreturn SlickOutcome::Throw(SlickFailure::slick(slick_value!(%s)));\n", indent, value)
	case "return":
		value, err := expression()
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "%sreturn SlickOutcome::Return(slick_value!(%s));\n", indent, value)
	case "expression":
		value, err := expression()
		if err != nil {
			return "", err
		}
		if last {
			fmt.Fprintf(&output, "%sreturn %s;\n", indent, value)
		} else {
			fmt.Fprintf(&output, "%slet _ = slick_value!(%s);\n", indent, value)
		}
	default:
		return "", rustLoweringError(statement.Location, "statement %s is not supported", statement.Kind)
	}
	return output.String(), nil
}

func (g *rustGenerator) expression(expression coreExpression, level int, scope string) (string, error) {
	raw, err := g.rawExpression(expression, level, scope)
	if err != nil {
		return "", err
	}
	for _, conversion := range []string{expression.Conversion, expression.ReadConversion} {
		if conversion != "" {
			raw = fmt.Sprintf("slick_convert(%s, %s)", raw, rustStringLiteral(conversion))
		}
	}
	return raw, nil
}

func (g *rustGenerator) rawExpression(expression coreExpression, level int, scope string) (string, error) {
	child := func(value *coreExpression) (string, error) {
		if value == nil {
			return "", rustLoweringError(expression.Location, "%s expression has no child", expression.Kind)
		}
		return g.expression(*value, level+1, scope)
	}
	switch expression.Kind {
	case "literal":
		if expression.Literal == nil {
			return "", rustLoweringError(expression.Location, "literal has no value")
		}
		value, err := g.literal(*expression.Literal)
		if err != nil {
			return "", rustLoweringError(expression.Location, "%v", err)
		}
		return "SlickOutcome::Value(" + value + ")", nil
	case "name":
		return g.nameExpression(expression), nil
	case "tuple", "array":
		values, lines, err := g.evaluatedExpressions(expression.Elements, level, scope)
		if err != nil {
			return "", err
		}
		kind := "Tuple"
		if expression.Kind == "array" {
			kind = "Array"
		}
		lines = append(lines, fmt.Sprintf("SlickOutcome::Value(SlickValue::%s(vec![%s]))", kind, strings.Join(values, ", ")))
		return rustInlineBlock(lines, level), nil
	case "map":
		lines := make([]string, 0, len(expression.Entries)*2+1)
		entries := make([]string, 0, len(expression.Entries))
		for _, entry := range expression.Entries {
			key, err := g.expression(entry.Key, level+1, scope)
			if err != nil {
				return "", err
			}
			keyName := g.nextTemporary()
			lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", keyName, key))
			value, err := g.expression(entry.Value, level+1, scope)
			if err != nil {
				return "", err
			}
			valueName := g.nextTemporary()
			lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", valueName, value))
			entries = append(entries, fmt.Sprintf("(%s, %s)", keyName, valueName))
		}
		lines = append(lines, fmt.Sprintf("SlickOutcome::Value(slick_map(vec![%s]))", strings.Join(entries, ", ")))
		return rustInlineBlock(lines, level), nil
	case "range":
		left, err := child(expression.Left)
		if err != nil {
			return "", err
		}
		right, err := child(expression.Right)
		if err != nil {
			return "", err
		}
		leftName, rightName := g.nextTemporary(), g.nextTemporary()
		return rustInlineBlock([]string{
			fmt.Sprintf("let %s = slick_value!(%s);", leftName, left),
			fmt.Sprintf("let %s = slick_value!(%s);", rightName, right),
			fmt.Sprintf("match (%s, %s) { (SlickValue::Int(start), SlickValue::Int(end)) => SlickOutcome::Value(SlickValue::Range(start, end)), _ => SlickOutcome::Throw(SlickFailure::host(\"range bounds are not int\")) }", leftName, rightName),
		}, level), nil
	case "template":
		lines := []string{"let mut slick_text = String::new();"}
		for _, part := range expression.Template {
			if part.Name == "" {
				lines = append(lines, fmt.Sprintf("slick_text.push_str(%s);", rustStringLiteral(part.Text)))
				continue
			}
			value := g.nameExpression(coreExpression{Name: part.Name, Declaration: part.Declaration})
			if part.ReadConversion != "" {
				value = fmt.Sprintf("slick_convert(%s, %s)", value, rustStringLiteral(part.ReadConversion))
			}
			name := g.nextTemporary()
			lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", name, value), fmt.Sprintf("slick_text.push_str(&slick_format(&%s));", name))
		}
		lines = append(lines, "SlickOutcome::Value(SlickValue::String(slick_text))")
		return rustInlineBlock(lines, level), nil
	case "object":
		lines := make([]string, 0, len(expression.Fields)+1)
		values := make(map[string]string, len(expression.Fields))
		order := make([]string, 0, len(expression.Fields))
		for _, field := range expression.Fields {
			value, err := g.expression(field.Value, level+1, scope)
			if err != nil {
				return "", err
			}
			name := g.nextTemporary()
			lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", name, value))
			values[field.Name] = name
			order = append(order, field.Name)
		}
		// An object literal may omit an optional field; the value still carries
		// every declared field, initialized to tagged absence.
		fields := make([]string, 0, len(expression.Fields))
		for _, field := range g.classes[expression.Declaration].Fields {
			value, ok := values[field.Name]
			if !ok {
				value = "SlickValue::Optional(None)"
				if !strings.HasSuffix(field.Type, "?") {
					value = "SlickValue::Null"
				}
			}
			delete(values, field.Name)
			fields = append(fields, fmt.Sprintf("(%s, %s)", rustStringLiteral(field.Name), value))
		}
		for _, name := range order {
			if value, ok := values[name]; ok {
				fields = append(fields, fmt.Sprintf("(%s, %s)", rustStringLiteral(name), value))
			}
		}
		lines = append(lines, fmt.Sprintf("SlickOutcome::Value(SlickValue::Object { type_name: %s, fields: vec![%s], resource: None, message: String::new() })",
			rustStringLiteral(expression.Declaration), strings.Join(fields, ", ")))
		return rustInlineBlock(lines, level), nil
	case "lambda":
		id := fmt.Sprintf("lambda.%d", len(g.lambdas))
		g.lambdas = append(g.lambdas, rustLambda{id: id, expression: expression})
		captures := make([]string, 0, len(expression.Captures))
		for _, capture := range expression.Captures {
			captures = append(captures, rustLocalName(capture.Name)+".clone()")
		}
		return fmt.Sprintf("SlickOutcome::Value(SlickValue::Callable(SlickCallable { target: %s, captures: vec![%s] }))", rustStringLiteral(id), strings.Join(captures, ", ")), nil
	case "call":
		return g.call(expression, level, scope)
	case "task_await":
		if scope == "" {
			return "", rustLoweringError(expression.Location, "await has no structured task scope")
		}
		return fmt.Sprintf("%s.await_task(%s)", scope, rustLocalName(expression.Name)), nil
	case "unary":
		value, err := child(expression.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("slick_unary(%s, slick_value!(%s))", rustStringLiteral(expression.Operator), value), nil
	case "binary":
		left, err := child(expression.Left)
		if err != nil {
			return "", err
		}
		if expression.ShortCircuit || expression.Operator == "&&" || expression.Operator == "||" {
			right, err := child(expression.Right)
			if err != nil {
				return "", err
			}
			leftName := g.nextTemporary()
			short, evaluate := "false", "!value"
			if expression.Operator == "||" {
				short, evaluate = "true", "value"
			}
			return rustInlineBlock([]string{
				fmt.Sprintf("let %s = slick_value!(%s);", leftName, left),
				fmt.Sprintf("match slick_truth(&%s) { Ok(value) if %s => SlickOutcome::Value(SlickValue::Bool(%s)), Ok(_) => %s, Err(failure) => SlickOutcome::Throw(failure) }", leftName, evaluate, short, right),
			}, level), nil
		}
		right, err := child(expression.Right)
		if err != nil {
			return "", err
		}
		leftName, rightName := g.nextTemporary(), g.nextTemporary()
		return rustInlineBlock([]string{
			fmt.Sprintf("let %s = slick_value!(%s);", leftName, left),
			fmt.Sprintf("let %s = slick_value!(%s);", rightName, right),
			fmt.Sprintf("slick_binary(%s, %s, %s)", rustStringLiteral(expression.Operator), leftName, rightName),
		}, level), nil
	case "branch":
		condition, err := child(expression.Value)
		if err != nil {
			return "", err
		}
		if expression.Body == nil || expression.Alternate == nil {
			return "", rustLoweringError(expression.Location, "branch has a missing arm")
		}
		body, err := g.block(*expression.Body, level+1, scope)
		if err != nil {
			return "", err
		}
		alternate, err := g.block(*expression.Alternate, level+1, scope)
		if err != nil {
			return "", err
		}
		name := g.nextTemporary()
		return rustInlineBlock([]string{
			fmt.Sprintf("let %s = slick_value!(%s);", name, condition),
			fmt.Sprintf("match slick_truth(&%s) { Ok(true) => %s, Ok(false) => %s, Err(failure) => SlickOutcome::Throw(failure) }", name, body, alternate),
		}, level), nil
	case "catch":
		return g.catchExpression(expression, level, scope)
	case "result":
		value, err := child(expression.Value)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("SlickOutcome::Value(SlickValue::Result(%t, Box::new(slick_value!(%s))))", expression.ResultVariant == "ok", value), nil
	case "propagate":
		value, err := child(expression.Value)
		if err != nil {
			return "", err
		}
		name := g.nextTemporary()
		return rustInlineBlock([]string{
			fmt.Sprintf("let %s = slick_value!(%s);", name, value),
			fmt.Sprintf("match %s { SlickValue::Result(true, value) => SlickOutcome::Value(*value), SlickValue::Result(false, value) => SlickOutcome::Return(SlickValue::Result(false, value)), _ => SlickOutcome::Throw(SlickFailure::host(\"propagation value is not Result\")) }", name),
		}, level), nil
	case "using":
		return g.usingExpression(expression, level, scope)
	case "match":
		return g.matchExpression(expression, level, scope)
	default:
		return "", rustLoweringError(expression.Location, "expression %s is not supported", expression.Kind)
	}
}

func (g *rustGenerator) nameExpression(expression coreExpression) string {
	if _, ok := g.constants[expression.Declaration]; ok {
		return fmt.Sprintf("SlickOutcome::Value(%s())", rustConstantName(expression.Declaration))
	}
	if variant, ok := g.variants[expression.Declaration]; ok {
		return fmt.Sprintf("SlickOutcome::Value(SlickValue::Union { type_name: %s, variant: %s, tag: %d, fields: vec![] })",
			rustStringLiteral(variant.union), rustStringLiteral(variant.name), variant.tag)
	}
	if _, ok := g.functions[expression.Declaration]; ok {
		return fmt.Sprintf("SlickOutcome::Value(SlickValue::Callable(SlickCallable { target: %s, captures: vec![] }))", rustStringLiteral(expression.Declaration))
	}
	return g.nameFromParts(expression.Name, expression.Declaration)
}

func (g *rustGenerator) nameFromParts(name, declaration string) string {
	parts := strings.Split(name, ".")
	if len(parts) == 0 || parts[0] == "" {
		return "SlickOutcome::Throw(SlickFailure::host(\"empty value name\"))"
	}
	base := rustLocalName(parts[0]) + ".clone()"
	if len(parts) == 1 {
		return "SlickOutcome::Value(" + base + ")"
	}
	path := make([]string, 0, len(parts)-1)
	for _, part := range parts[1:] {
		path = append(path, rustStringLiteral(part))
	}
	return fmt.Sprintf("slick_path(%s, &[%s])", base, strings.Join(path, ", "))
}

func (g *rustGenerator) call(expression coreExpression, level int, scope string) (string, error) {
	if strings.HasPrefix(expression.Declaration, "core.") {
		return g.coreCall(expression, level, scope)
	}
	if expression.Operation != "" {
		return g.standardCall(expression, level, scope)
	}
	if variant, ok := g.variants[expression.Declaration]; ok {
		values, lines, err := g.evaluatedExpressions(expression.Arguments, level, scope)
		if err != nil {
			return "", err
		}
		lines = append(lines, fmt.Sprintf("SlickOutcome::Value(SlickValue::Union { type_name: %s, variant: %s, tag: %d, fields: vec![%s] })",
			rustStringLiteral(variant.union), rustStringLiteral(variant.name), variant.tag, strings.Join(values, ", ")))
		return rustInlineBlock(lines, level), nil
	}
	// An error class doubles as a shorthand constructor whose single argument is
	// only the failure message: no declared field is set, so the text travels in
	// the value's failure metadata instead.
	if g.errorClasses[expression.Declaration] {
		values, lines, err := g.evaluatedExpressions(expression.Arguments, level, scope)
		if err != nil {
			return "", err
		}
		message := "String::new()"
		if len(values) > 0 {
			message = fmt.Sprintf("slick_format(&%s)", values[0])
		}
		lines = append(lines, fmt.Sprintf("SlickOutcome::Value(SlickValue::Object { type_name: %s, fields: vec![], resource: None, message: %s })",
			rustStringLiteral(expression.Declaration), message))
		return rustInlineBlock(lines, level), nil
	}
	lines := make([]string, 0, len(expression.Arguments)+3)
	callee := ""
	receiver := ""
	if expression.Value != nil {
		value, err := g.expression(*expression.Value, level+1, scope)
		if err != nil {
			return "", err
		}
		callee = g.nextTemporary()
		lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", callee, value))
	} else if expression.Receiver != nil {
		value, err := g.expression(*expression.Receiver, level+1, scope)
		if err != nil {
			return "", err
		}
		receiver = g.nextTemporary()
		lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", receiver, value))
	}
	arguments, argumentLines, err := g.evaluatedExpressions(expression.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	lines = append(lines, argumentLines...)
	switch {
	case callee != "":
		lines = append(lines, fmt.Sprintf("slick_call_callable(slick_context, %s, vec![%s])", callee, strings.Join(arguments, ", ")))
	case receiver != "":
		lines = append(lines, fmt.Sprintf("slick_call_method(slick_context, %s, %s, vec![%s])", receiver, rustStringLiteral(expression.Declaration), strings.Join(arguments, ", ")))
	case expression.Declaration != "":
		if _, ok := g.functions[expression.Declaration]; !ok {
			return "", rustLoweringError(expression.Location, "unknown function %s", expression.Declaration)
		}
		lines = append(lines, fmt.Sprintf("%s(slick_context, None, vec![%s])", rustFunctionName(expression.Declaration), strings.Join(arguments, ", ")))
	default:
		return "", rustLoweringError(expression.Location, "call has no target")
	}
	return rustInlineBlock(lines, level), nil
}

func (g *rustGenerator) coreCall(expression coreExpression, level int, scope string) (string, error) {
	values, lines, err := g.evaluatedExpressions(expression.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	switch expression.Declaration {
	case "core.enumerate":
		if len(values) != 1 {
			return "", rustLoweringError(expression.Location, "enumerate expects one argument")
		}
		lines = append(lines, fmt.Sprintf("SlickOutcome::Value(SlickValue::Enumerate(Box::new(%s)))", values[0]))
	case "core.zip":
		lines = append(lines, fmt.Sprintf("SlickOutcome::Value(SlickValue::Zip(vec![%s]))", strings.Join(values, ", ")))
	case "core.unwrap":
		if len(values) != 1 {
			return "", rustLoweringError(expression.Location, "unwrap expects one argument")
		}
		lines = append(lines, fmt.Sprintf("match %s { SlickValue::Result(true, value) => SlickOutcome::Value(*value), SlickValue::Result(false, value) => SlickOutcome::Throw(SlickFailure::slick(*value)), _ => SlickOutcome::Throw(SlickFailure::host(\"unwrap value is not Result\")) }", values[0]))
	default:
		return "", rustLoweringError(expression.Location, "compiler operation %s is not supported", expression.Declaration)
	}
	return rustInlineBlock(lines, level), nil
}

// standardCall lowers one compiler-owned standard-library operation. A method
// operation receives its receiver as the first argument, so every family
// implements one uniform Rust entry point.
func (g *rustGenerator) standardCall(expression coreExpression, level int, scope string) (string, error) {
	function, ok := rustStdFunction(expression.Operation)
	if !ok {
		return "", rustLoweringError(expression.Location, "standard-library operation %s is not supported", expression.Operation)
	}
	lines := make([]string, 0, len(expression.Arguments)+2)
	values := make([]string, 0, len(expression.Arguments)+1)
	if expression.Receiver != nil {
		receiver, err := g.expression(*expression.Receiver, level+1, scope)
		if err != nil {
			return "", err
		}
		name := g.nextTemporary()
		lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", name, receiver))
		values = append(values, name)
	}
	arguments, argumentLines, err := g.evaluatedExpressions(expression.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	lines = append(lines, argumentLines...)
	values = append(values, arguments...)
	// A generic standard-library operation receives its resolved type arguments
	// after the declared parameters, so typed behavior such as JSON decoding is
	// driven by the checked type rather than inferred from the payload.
	for _, typeArgument := range expression.TypeArguments {
		values = append(values, fmt.Sprintf("SlickValue::String(%s.to_string())", rustStringLiteral(typeArgument)))
	}
	lines = append(lines, fmt.Sprintf("%s(slick_context, vec![%s])", function, strings.Join(values, ", ")))
	return rustInlineBlock(lines, level), nil
}

func (g *rustGenerator) evaluatedExpressions(expressions []coreExpression, level int, scope string) ([]string, []string, error) {
	values := make([]string, 0, len(expressions))
	lines := make([]string, 0, len(expressions))
	for _, expression := range expressions {
		value, err := g.expression(expression, level+1, scope)
		if err != nil {
			return nil, nil, err
		}
		name := g.nextTemporary()
		lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", name, value))
		values = append(values, name)
	}
	return values, lines, nil
}

func (g *rustGenerator) catchExpression(expression coreExpression, level int, scope string) (string, error) {
	value, err := g.expression(*expression.Value, level+1, scope)
	if err != nil {
		return "", err
	}
	failure := g.nextTemporary()
	var output strings.Builder
	output.WriteString("{\n")
	fmt.Fprintf(&output, "%smatch %s {\n", rustIndent(level+1), value)
	fmt.Fprintf(&output, "%sSlickOutcome::Throw(%s) => {\n", rustIndent(level+2), failure)
	for _, arm := range expression.Arms {
		fmt.Fprintf(&output, "%sif slick_match_failure(&%s, %s) {\n", rustIndent(level+3), failure, rustStringLiteral(arm.Pattern))
		for _, binding := range arm.Bindings {
			if binding.Name != "_" {
				fmt.Fprintf(&output, "%slet mut %s = slick_failure_value(&%s);\n", rustIndent(level+4), rustLocalName(binding.Name), failure)
			}
		}
		armValue, err := g.expression(arm.Value, level+4, scope)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "%s%s\n%s} else ", rustIndent(level+4), armValue, rustIndent(level+3))
	}
	fmt.Fprintf(&output, "{ SlickOutcome::Throw(%s) }\n", failure)
	fmt.Fprintf(&output, "%s}\n%soutcome => outcome,\n%s}\n%s}", rustIndent(level+2), rustIndent(level+2), rustIndent(level+1), rustIndent(level))
	return output.String(), nil
}

func (g *rustGenerator) usingExpression(expression coreExpression, level int, scope string) (string, error) {
	if expression.Value == nil || expression.Body == nil || len(expression.Bindings) != 1 {
		return "", rustLoweringError(expression.Location, "invalid using expression")
	}
	initializer, err := g.expression(*expression.Value, level+1, scope)
	if err != nil {
		return "", err
	}
	resource := g.nextTemporary()
	body, err := g.block(*expression.Body, level+1, scope)
	if err != nil {
		return "", err
	}
	binding := rustLocalName(expression.Bindings[0].Name)
	return rustInlineBlock([]string{
		fmt.Sprintf("let %s = slick_value!(%s);", resource, initializer),
		fmt.Sprintf("let slick_primary = { let mut %s = %s.clone(); %s };", binding, resource, body),
		// Cleanup runs with cancellation detached, so a cancelled scope still
		// closes its resource.
		fmt.Sprintf("let slick_cleanup = slick_call_method(&slick_context.without_cancel(), %s, \"Close\", vec![]);", resource),
		"slick_combine_outcomes(slick_primary, slick_cleanup)",
	}, level), nil
}

func (g *rustGenerator) matchExpression(expression coreExpression, level int, scope string) (string, error) {
	if expression.Value == nil {
		return "", rustLoweringError(expression.Location, "match has no value")
	}
	value, err := g.expression(*expression.Value, level+1, scope)
	if err != nil {
		return "", err
	}
	scrutinee := g.nextTemporary()
	var output strings.Builder
	output.WriteString("{\n")
	fmt.Fprintf(&output, "%slet %s = slick_value!(%s);\n", rustIndent(level+1), scrutinee, value)
	for index, arm := range expression.Arms {
		prefix := "if"
		if index > 0 {
			prefix = "else if"
		}
		condition := "true"
		payload := ""
		switch arm.Pattern {
		case "variant":
			variant, _ := coreDeclarationName(arm.Variant)
			payload = g.nextTemporary()
			condition = fmt.Sprintf("let Some(%s) = slick_union_payload(%s.clone(), %s)", payload, scrutinee, rustStringLiteral(variant))
		case "Ok":
			payload = g.nextTemporary()
			condition = fmt.Sprintf("let Some(%s) = slick_result_payload(%s.clone(), true)", payload, scrutinee)
		case "Err":
			payload = g.nextTemporary()
			condition = fmt.Sprintf("let Some(%s) = slick_result_payload(%s.clone(), false)", payload, scrutinee)
		}
		fmt.Fprintf(&output, "%s%s %s {\n", rustIndent(level+1), prefix, condition)
		for bindingIndex, binding := range arm.Bindings {
			if binding.Name == "_" {
				continue
			}
			if arm.Pattern == "variant" {
				fmt.Fprintf(&output, "%slet mut %s = %s.get(%d).cloned().unwrap_or(SlickValue::Null);\n", rustIndent(level+2), rustLocalName(binding.Name), payload, bindingIndex)
			} else if payload != "" {
				fmt.Fprintf(&output, "%slet mut %s = %s.clone();\n", rustIndent(level+2), rustLocalName(binding.Name), payload)
			} else {
				fmt.Fprintf(&output, "%slet mut %s = %s.clone();\n", rustIndent(level+2), rustLocalName(binding.Name), scrutinee)
			}
		}
		armValue, err := g.expression(arm.Value, level+2, scope)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "%s%s\n%s}", rustIndent(level+2), armValue, rustIndent(level+1))
		if index == len(expression.Arms)-1 {
			output.WriteByte('\n')
		}
	}
	fmt.Fprintf(&output, "%selse { SlickOutcome::Throw(SlickFailure::host(\"non-exhaustive match\")) }\n%s}", rustIndent(level+1), rustIndent(level))
	return output.String(), nil
}

func (g *rustGenerator) taskLaunch(call coreExpression, level int, scope string) (string, error) {
	if call.Kind != "call" {
		return "", rustLoweringError(call.Location, "task launch target is not a call")
	}
	native := ""
	if call.Operation != "" {
		function, ok := rustStdFunction(call.Operation)
		if !ok {
			return "", rustLoweringError(call.Location, "standard-library operation %s is not supported", call.Operation)
		}
		native = function
	}
	lines := make([]string, 0, len(call.Arguments)+3)
	callee := ""
	receiver := ""
	if call.Value != nil {
		value, err := g.expression(*call.Value, level+1, scope)
		if err != nil {
			return "", err
		}
		callee = g.nextTemporary()
		lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", callee, value))
	} else if call.Receiver != nil {
		value, err := g.expression(*call.Receiver, level+1, scope)
		if err != nil {
			return "", err
		}
		receiver = g.nextTemporary()
		lines = append(lines, fmt.Sprintf("let %s = slick_value!(%s);", receiver, value))
	}
	arguments, argumentLines, err := g.evaluatedExpressions(call.Arguments, level, scope)
	if err != nil {
		return "", err
	}
	lines = append(lines, argumentLines...)
	work := ""
	switch {
	case native != "":
		// A launched standard-library operation runs its compiler-owned entry
		// point in the child scope, receiving the same receiver-first arguments.
		values := arguments
		if receiver != "" {
			values = append([]string{receiver}, arguments...)
		}
		for _, typeArgument := range call.TypeArguments {
			values = append(values, fmt.Sprintf("SlickValue::String(%s.to_string())", rustStringLiteral(typeArgument)))
		}
		work = fmt.Sprintf("move |child_context| %s(&child_context, vec![%s])", native, strings.Join(values, ", "))
	case callee != "":
		work = fmt.Sprintf("move |child_context| slick_call_callable(&child_context, %s, vec![%s])", callee, strings.Join(arguments, ", "))
	case receiver != "":
		work = fmt.Sprintf("move |child_context| slick_call_method(&child_context, %s, %s, vec![%s])", receiver, rustStringLiteral(call.Declaration), strings.Join(arguments, ", "))
	default:
		work = fmt.Sprintf("move |child_context| %s(&child_context, None, vec![%s])", rustFunctionName(call.Declaration), strings.Join(arguments, ", "))
	}
	lines = append(lines, fmt.Sprintf("match %s.launch(%s) { Ok(task) => task, Err(failure) => return SlickOutcome::Throw(failure) }", scope, work))
	return rustPlainBlock(lines, level), nil
}

func (g *rustGenerator) callableDispatcher() (string, error) {
	var output strings.Builder
	output.WriteString("fn slick_call_callable(slick_context: &SlickContext, slick_value: SlickValue, slick_arguments: Vec<SlickValue>) -> SlickOutcome {\n")
	output.WriteString("    let SlickValue::Callable(slick_callable) = slick_value else { return SlickOutcome::Throw(SlickFailure::host(\"value is not callable\")); };\n")
	output.WriteString("    match slick_callable.target {\n")
	for _, function := range g.core.Functions {
		if function.Receiver == "" {
			fmt.Fprintf(&output, "        %s => %s(slick_context, None, slick_arguments),\n", rustStringLiteral(function.ID), rustFunctionName(function.ID))
		}
	}
	for index := 0; index < len(g.lambdas); index++ {
		lambda := g.lambdas[index]
		fmt.Fprintf(&output, "        %s => {\n", rustStringLiteral(lambda.id))
		for captureIndex, capture := range lambda.expression.Captures {
			fmt.Fprintf(&output, "            let Some(mut %s) = slick_callable.captures.get(%d).cloned() else { return SlickOutcome::Throw(SlickFailure::host(\"missing lambda capture\")); };\n", rustLocalName(capture.Name), captureIndex)
		}
		for parameterIndex, parameter := range lambda.expression.Parameters {
			fmt.Fprintf(&output, "            let Some(mut %s) = slick_arguments.get(%d).cloned() else { return SlickOutcome::Throw(SlickFailure::host(\"missing lambda argument\")); };\n", rustLocalName(parameter.Name), parameterIndex)
		}
		if lambda.expression.Body == nil {
			return "", rustLoweringError(lambda.expression.Location, "lambda has no body")
		}
		body, err := g.block(*lambda.expression.Body, 3, "")
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&output, "            slick_finish_function(%s)\n", body)
		output.WriteString("        },\n")
	}
	output.WriteString("        _ => SlickOutcome::Throw(SlickFailure::host(\"unknown callable target\")),\n")
	output.WriteString("    }\n}\n")
	return output.String(), nil
}

func (g *rustGenerator) methodDispatcher() string {
	var output strings.Builder
	output.WriteString("fn slick_call_method(slick_context: &SlickContext, slick_receiver: SlickValue, slick_method: &str, slick_arguments: Vec<SlickValue>) -> SlickOutcome {\n")
	output.WriteString("    if let Some(outcome) = slick_builtin_method(&slick_receiver, slick_method, &slick_arguments) { return outcome; }\n")
	output.WriteString("    let slick_receiver_type = slick_type_name(&slick_receiver);\n")
	output.WriteString("    let slick_method_name = slick_method.rsplit('.').next().unwrap_or(slick_method);\n")
	output.WriteString("    match (slick_receiver_type, slick_method_name) {\n")
	for _, function := range g.core.Functions {
		if function.Receiver == "" {
			continue
		}
		name, _ := coreDeclarationName(function.ID)
		fmt.Fprintf(&output, "        (%s, %s) => %s(slick_context, Some(slick_receiver), slick_arguments),\n", rustStringLiteral(function.Receiver), rustStringLiteral(name), rustFunctionName(function.ID))
	}
	// Native resource methods are intentionally absent from core.Functions (they
	// have no Slick body), so using-scope cleanup and interface-typed calls reach
	// them through these compiler-owned native entry points. Each method receives
	// its receiver as args[0] followed by the declared parameters, exactly like a
	// direct standard-library method call. Only linked families are dispatched,
	// because only their runtime modules are emitted.
	for _, class := range g.core.Classes {
		for _, method := range class.Methods {
			if method.Operation == "" {
				continue
			}
			native, ok := rustStdFunction(method.Operation)
			if !ok || !g.runtime.families[runtimeOperationRegistry[method.Operation].family] {
				continue
			}
			name, _ := coreDeclarationName(method.ID)
			fmt.Fprintf(&output, "        (%s, %s) => { let mut slick_method_args = vec![slick_receiver]; slick_method_args.extend(slick_arguments); %s(slick_context, slick_method_args) },\n",
				rustStringLiteral(class.ID), rustStringLiteral(name), native)
		}
	}
	output.WriteString("        _ => SlickOutcome::Throw(SlickFailure::host(format!(\"method {slick_method} is unavailable on {slick_receiver_type}\"))),\n")
	output.WriteString("    }\n}\n")
	return output.String()
}

// mainFunction renders the process entry point. A command-line main receives the
// argument vector without the executable name, and a std.process.Status result
// writes its exact bytes before the exit code is validated.
func (g *rustGenerator) mainFunction() string {
	main := g.functions["root.main"]
	var output strings.Builder
	output.WriteString("fn main() {\n")
	arguments := "vec![]"
	if len(main.Parameters) == 1 {
		// A non-UTF-8 argument is rendered deterministically instead of aborting
		// before the program starts.
		output.WriteString("    let slick_arguments = SlickValue::Array(std::env::args_os().skip(1)\n")
		output.WriteString("        .map(|argument| SlickValue::String(argument.to_string_lossy().into_owned())).collect());\n")
		arguments = "vec![slick_arguments]"
	}
	fmt.Fprintf(&output, "    let outcome = %s(&SlickContext::root(), None, %s);\n", rustFunctionName("root.main"), arguments)
	output.WriteString("    let value = match outcome {\n")
	output.WriteString("        SlickOutcome::Value(value) | SlickOutcome::Return(value) => value,\n")
	output.WriteString("        SlickOutcome::Throw(failure) => { eprintln!(\"{}\", slick_failure_text(&failure)); std::process::exit(1); },\n")
	output.WriteString("        SlickOutcome::Break | SlickOutcome::Continue => { eprintln!(\"invalid control flow\"); std::process::exit(1); },\n")
	output.WriteString("    };\n")
	if main.Result == stdProcessStatusName {
		output.WriteString("    let output = match slick_field(&value, \"Output\") { Ok(SlickValue::Bytes(bytes)) => bytes, _ => Vec::new() };\n")
		output.WriteString("    let error_output = match slick_field(&value, \"ErrorOutput\") { Ok(SlickValue::Bytes(bytes)) => bytes, _ => Vec::new() };\n")
		output.WriteString("    let code = match slick_field(&value, \"ExitCode\") { Ok(SlickValue::Int(code)) => code, _ => 0 };\n")
		output.WriteString("    use std::io::Write;\n")
		output.WriteString("    let _ = std::io::stdout().write_all(&output);\n")
		output.WriteString("    let _ = std::io::stdout().flush();\n")
		output.WriteString("    let _ = std::io::stderr().write_all(&error_output);\n")
		fmt.Fprintf(&output, "        if code < %d || code > %d {\n", minExitCode, maxExitCode)
		fmt.Fprintf(&output, "        eprintln!(\"%s, found {}\", code);\n", invalidExitCodeMessage)
		output.WriteString("        std::process::exit(1);\n    }\n")
		output.WriteString("    std::process::exit(code as i32);\n}\n")
		return output.String()
	}
	output.WriteString("    let text = slick_format(&value);\n")
	output.WriteString("    if !text.is_empty() { println!(\"{}\", text); }\n")
	output.WriteString("}\n")
	return output.String()
}

func (g *rustGenerator) literal(literal coreLiteral) (string, error) {
	switch literal.Kind {
	case "null":
		return "SlickValue::Null", nil
	case "bool":
		return "SlickValue::Bool(" + strconv.FormatBool(literal.Boolean) + ")", nil
	case "int":
		return "SlickValue::Int(" + strconv.FormatInt(literal.Integer, 10) + "i64)", nil
	case "float":
		return fmt.Sprintf("SlickValue::Float(f64::from_bits(0x%016x))", math.Float64bits(literal.Float)), nil
	case "string":
		return "SlickValue::String(" + rustStringLiteral(literal.Text) + ".to_string())", nil
	case "union":
		variant, ok := g.variants[literal.Variant]
		if !ok {
			return "", fmt.Errorf("unknown union literal %s", literal.Variant)
		}
		return fmt.Sprintf("SlickValue::Union { type_name: %s, variant: %s, tag: %d, fields: vec![] }", rustStringLiteral(variant.union), rustStringLiteral(variant.name), variant.tag), nil
	default:
		return "", fmt.Errorf("literal kind %s is not supported", literal.Kind)
	}
}

func (g *rustGenerator) nextTemporary() string {
	name := fmt.Sprintf("slick_tmp_%d", g.temporary)
	g.temporary++
	return name
}

func rustInlineBlock(lines []string, level int) string {
	var output strings.Builder
	output.WriteString("(|| -> SlickOutcome {\n")
	for _, line := range lines {
		fmt.Fprintf(&output, "%s%s\n", rustIndent(level+1), line)
	}
	fmt.Fprintf(&output, "%s})()", rustIndent(level))
	return output.String()
}

func rustPlainBlock(lines []string, level int) string {
	var output strings.Builder
	output.WriteString("{\n")
	for _, line := range lines {
		fmt.Fprintf(&output, "%s%s\n", rustIndent(level+1), line)
	}
	fmt.Fprintf(&output, "%s}", rustIndent(level))
	return output.String()
}

func rustStringLiteral(value string) string {
	var output strings.Builder
	output.WriteByte('"')
	for len(value) > 0 {
		r, size := utf8.DecodeRuneInString(value)
		value = value[size:]
		switch r {
		case '\\':
			output.WriteString("\\\\")
		case '"':
			output.WriteString("\\\"")
		case '\n':
			output.WriteString("\\n")
		case '\r':
			output.WriteString("\\r")
		case '\t':
			output.WriteString("\\t")
		case '\x00':
			output.WriteString("\\0")
		default:
			if r < 0x20 || r == 0x7f || (r >= '\u202a' && r <= '\u202e') ||
				(r >= '\u2066' && r <= '\u2069') {
				fmt.Fprintf(&output, "\\u{%x}", r)
			} else {
				output.WriteRune(r)
			}
		}
	}
	output.WriteByte('"')
	return output.String()
}

func rustFunctionName(name string) string { return "slick_fn_" + hex.EncodeToString([]byte(name)) }
func rustConstantName(name string) string {
	return "slick_const_" + hex.EncodeToString([]byte(name))
}
func rustLocalName(name string) string { return "slick_local_" + hex.EncodeToString([]byte(name)) }
func rustIndent(level int) string      { return strings.Repeat("    ", level) }
