package compiler

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const (
	rustToolchainVersion = "1.93.1"
	rustTargetTriple     = "x86_64-unknown-linux-gnu"
	rustToolchainName    = rustToolchainVersion + "-" + rustTargetTriple
	rustPackageName      = "slick_program"
)

const rustCargoManifest = `[package]
name = "slick_program"
version = "0.0.0"
edition = "2024"
publish = false

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
`

const rustCargoLock = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "slick_program"
version = "0.0.0"
`

func rustBackendDriver() backendDriver {
	return backendDriver{
		checkCore: func(input backendDriverInput) error {
			return validateRustCore(input.core, input.runtime)
		},
		validate: validateRustToolchain,
		emit: func(input backendDriverInput, workspace string) (backendEmission, error) {
			emission, err := emitRustWorkspace(input.core, workspace)
			if err != nil {
				return backendEmission{}, rustBackendBuildError(input, err)
			}
			return emission, nil
		},
		build: func(input backendDriverInput, emission backendEmission, candidate string) error {
			if err := buildRustEmission(input, emission, candidate); err != nil {
				return rustBackendBuildError(input, err)
			}
			return nil
		},
		verify: verifyNativeExecutable,
	}
}

func rustBackendBuildError(input backendDriverInput, err error) error {
	return fmt.Errorf("Rust backend (%s %s, target %s): %w",
		input.toolchain.registration.name, input.toolchain.version, input.target.name, err)
}

func validateRustToolchain(input backendDriverInput) (backendToolchain, error) {
	if input.target.name != rustTargetTriple {
		return backendToolchain{}, fmt.Errorf("Rust target %s is unsupported; need %s", input.target.name, rustTargetTriple)
	}
	rustc, err := exec.LookPath("rustc")
	if err != nil {
		return backendToolchain{}, fmt.Errorf("Rust toolchain not found: need rustc %s and cargo %s for target %s", rustToolchainVersion, rustToolchainVersion, rustTargetTriple)
	}
	cargo, err := exec.LookPath("cargo")
	if err != nil {
		return backendToolchain{}, fmt.Errorf("Rust toolchain not found: need rustc %s and cargo %s for target %s", rustToolchainVersion, rustToolchainVersion, rustTargetTriple)
	}
	if err := requireRustToolVersion(rustc, "rustc", rustToolchainVersion); err != nil {
		return backendToolchain{}, err
	}
	if err := requireRustToolVersion(cargo, "cargo", rustToolchainVersion); err != nil {
		return backendToolchain{}, err
	}
	verbose, err := rustToolCommand(rustc, "-vV").CombinedOutput()
	if err != nil {
		return backendToolchain{}, fmt.Errorf("inspect rustc target: %w: %s", err, strings.TrimSpace(string(verbose)))
	}
	host := ""
	for _, line := range strings.Split(string(verbose), "\n") {
		if strings.HasPrefix(line, "host: ") {
			host = strings.TrimSpace(strings.TrimPrefix(line, "host: "))
			break
		}
	}
	if host != rustTargetTriple {
		return backendToolchain{}, fmt.Errorf("rustc %s targets %s; need %s", rustToolchainVersion, host, rustTargetTriple)
	}
	return backendToolchain{
		registration: input.target.toolchain,
		executables:  map[string]string{"rustc": rustc, "cargo": cargo},
		version:      rustToolchainVersion,
	}, nil
}

func requireRustToolVersion(path, name, want string) error {
	output, err := rustToolCommand(path, "--version").CombinedOutput()
	if err != nil {
		return fmt.Errorf("inspect %s version: %w: %s", name, err, strings.TrimSpace(string(output)))
	}
	found := ""
	for _, line := range strings.Split(string(output), "\n") {
		fields := strings.Fields(line)
		if len(fields) >= 2 && fields[0] == name {
			found = strings.TrimSpace(line)
			if fields[1] == want {
				return nil
			}
		}
	}
	if found == "" {
		found = strings.TrimSpace(string(output))
	}
	return fmt.Errorf("unsupported %s toolchain %q; need %s %s for target %s", name, found, name, want, rustTargetTriple)
}

func rustToolCommand(path string, arguments ...string) *exec.Cmd {
	command := exec.Command(path, arguments...)
	command.Dir = string(filepath.Separator)
	command.Env = rustBuildEnvironment(os.Environ(), map[string]string{
		"RUSTUP_TOOLCHAIN": rustToolchainName,
	})
	return command
}

func emitRustWorkspace(core coreProgram, workspace string) (backendEmission, error) {
	runtime, err := runtimeInputsForCore(core)
	if err != nil {
		return backendEmission{}, err
	}
	source, err := generateRust(core)
	if err != nil {
		return backendEmission{}, err
	}
	sourceDirectory := filepath.Join(workspace, "src")
	if err := os.MkdirAll(sourceDirectory, 0o755); err != nil {
		return backendEmission{}, fmt.Errorf("create Rust source directory: %w", err)
	}
	manifest := filepath.Join(workspace, "Cargo.toml")
	files := []struct {
		path string
		data string
	}{
		{path: manifest, data: rustCargoManifestFor(runtime)},
		{path: filepath.Join(workspace, "Cargo.lock"), data: rustCargoLockFor(runtime)},
		{path: filepath.Join(sourceDirectory, "main.rs"), data: source},
	}
	for _, file := range files {
		if err := os.WriteFile(file.path, []byte(file.data), 0o644); err != nil {
			return backendEmission{}, fmt.Errorf("write compiler-owned Rust workspace: %w", err)
		}
	}
	return backendEmission{primary: manifest}, nil
}

func buildRustEmission(input backendDriverInput, emission backendEmission, candidate string) error {
	workspace, err := filepath.Abs(filepath.Dir(emission.primary))
	if err != nil {
		return fmt.Errorf("resolve compiler-owned Rust workspace: %w", err)
	}
	manifest := filepath.Join(workspace, "Cargo.toml")
	cargoHome := filepath.Join(workspace, ".cargo-home")
	targetDirectory := filepath.Join(workspace, "target")
	if err := os.MkdirAll(cargoHome, 0o755); err != nil {
		return fmt.Errorf("create compiler-owned Cargo home: %w", err)
	}
	dependencies := len(rustStdCrates(input.runtime)) > 0
	if dependencies {
		// A program that links a compiler-owned crate resolves it from the pinned
		// lockfile before any output is installed, so a missing dependency fails
		// the build instead of producing a partial artifact.
		fetch := exec.Command(input.toolchain.executables["cargo"],
			"fetch", "--locked", "--target", rustTargetTriple, "--manifest-path", manifest)
		fetch.Dir = filepath.VolumeName(workspace) + string(filepath.Separator)
		fetch.Env = rustBuildEnvironment(os.Environ(), map[string]string{
			"CARGO_HOME":       cargoHome,
			"CARGO_TARGET_DIR": targetDirectory,
			"RUSTC":            input.toolchain.executables["rustc"],
			"RUSTUP_TOOLCHAIN": rustToolchainName,
		})
		if output, err := fetch.CombinedOutput(); err != nil {
			return fmt.Errorf("resolve compiler-owned Rust dependencies for target %s: %w: %s",
				rustTargetTriple, err, strings.TrimSpace(string(output)))
		}
	}
	arguments := []string{"build", "--locked", "--release", "--target", rustTargetTriple, "--manifest-path", manifest}
	if !dependencies {
		arguments = append([]string{"build", "--frozen", "--offline"}, arguments[1:]...)
	}
	command := exec.Command(input.toolchain.executables["cargo"], arguments...)
	// The build runs from the filesystem root so a caller project's Cargo
	// configuration can never reach the compiler-owned workspace.
	command.Dir = filepath.VolumeName(workspace) + string(filepath.Separator)
	rustFlags := strings.Join([]string{
		"--remap-path-prefix=" + workspace + "=/slick",
		"-C", "debuginfo=0",
		"-C", "strip=symbols",
		"-C", "codegen-units=1",
		"-C", "metadata=slick_runtime_v1",
	}, "\x1f")
	offline := "true"
	if dependencies {
		offline = "false"
	}
	command.Env = rustBuildEnvironment(os.Environ(), map[string]string{
		"CARGO_ENCODED_RUSTFLAGS": rustFlags,
		"CARGO_HOME":              cargoHome,
		"CARGO_INCREMENTAL":       "0",
		"CARGO_NET_OFFLINE":       offline,
		"CARGO_TARGET_DIR":        targetDirectory,
		"RUSTC":                   input.toolchain.executables["rustc"],
		"RUSTUP_TOOLCHAIN":        rustToolchainName,
		"SOURCE_DATE_EPOCH":       "0",
	})
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("cargo build: %w: %s", err, strings.TrimSpace(string(output)))
	}
	built := filepath.Join(targetDirectory, rustTargetTriple, "release", rustPackageName)
	if err := os.Link(built, candidate); err != nil {
		return fmt.Errorf("stage Cargo artifact: %w", err)
	}
	return nil
}

func rustBuildEnvironment(environment []string, controlled map[string]string) []string {
	result := make([]string, 0, len(environment)+len(controlled))
	for _, entry := range environment {
		name, _, _ := strings.Cut(entry, "=")
		if strings.HasPrefix(name, "CARGO_") {
			continue
		}
		switch name {
		case "AR", "CC", "CFLAGS", "CXX", "CXXFLAGS", "RUSTC", "RUSTC_BOOTSTRAP",
			"RUSTC_WRAPPER", "RUSTC_WORKSPACE_WRAPPER", "RUSTDOCFLAGS", "RUSTFLAGS",
			"RUSTUP_TOOLCHAIN", "SOURCE_DATE_EPOCH":
			continue
		}
		result = append(result, entry)
	}
	names := make([]string, 0, len(controlled))
	for name := range controlled {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		result = append(result, name+"="+controlled[name])
	}
	return result
}
